//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.18444
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace net.sxtrader.bftradingstrategies.tippsters {
    using System;
    
    
    /// <summary>
    ///   Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    /// </summary>
    // Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    // -Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    // Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    // mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class LayerOfProfit {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal LayerOfProfit() {
        }
        
        /// <summary>
        ///   Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("net.sxtrader.bftradingstrategies.tippsters.LayerOfProfit", typeof(LayerOfProfit).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        ///   Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Cannot place bet for Horse {0} at Race {1} at {2} because bet amount {3} is below Minimus Stake and Sport Exchange {4} does not support betting below minstake. ähnelt.
        /// </summary>
        internal static string strBelowMinStake {
            get {
                return ResourceManager.GetString("strBelowMinStake", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Tipster Layer Of Profit ähnelt.
        /// </summary>
        internal static string strDescription {
            get {
                return ResourceManager.GetString("strDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Could not connect to the mail server. Please check the settings for Host, Port and SSL ähnelt.
        /// </summary>
        internal static string strDonnotConnect {
            get {
                return ResourceManager.GetString("strDonnotConnect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Tipp &quot;Race {0} with Horse {1} at {2}&quot; is in the past. No Trade will be placed. ähnelt.
        /// </summary>
        internal static string strEventInPast {
            get {
                return ResourceManager.GetString("strEventInPast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Horse/Layer Of Profit ähnelt.
        /// </summary>
        internal static string strFQLayerOfProfit {
            get {
                return ResourceManager.GetString("strFQLayerOfProfit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Could not find horse {0} for race {1}  at {3} in market {2} ähnelt.
        /// </summary>
        internal static string strHorseNotFound {
            get {
                return ResourceManager.GetString("strHorseNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Horse {0} at Race {1} at {2}: Invalid Odds ähnelt.
        /// </summary>
        internal static string strInvalidOdds {
            get {
                return ResourceManager.GetString("strInvalidOdds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Could not log into the mail server.  Please check settings for User and Password. ähnelt.
        /// </summary>
        internal static string strMailLoginFailed {
            get {
                return ResourceManager.GetString("strMailLoginFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Layer Of Profit ähnelt.
        /// </summary>
        internal static string strName {
            get {
                return ResourceManager.GetString("strName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Could not find market for Race {0} with Horse {1} at {2} ähnelt.
        /// </summary>
        internal static string strNoMarketFound {
            get {
                return ResourceManager.GetString("strNoMarketFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Could not get Price Information for Horse {0} at Race {1} at {2} ähnelt.
        /// </summary>
        internal static string strNoPriceInformation {
            get {
                return ResourceManager.GetString("strNoPriceInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die No Selection Day ähnelt.
        /// </summary>
        internal static string strNoSelectionDay {
            get {
                return ResourceManager.GetString("strNoSelectionDay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Kein Tip gefunden ähnelt.
        /// </summary>
        internal static string strNoTippFound {
            get {
                return ResourceManager.GetString("strNoTippFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Plugin {0} loaded ähnelt.
        /// </summary>
        internal static string strPluginLoaded {
            get {
                return ResourceManager.GetString("strPluginLoaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die There was a mismatch of selectionIds for a Layer Of Profit Tipp. Selection ID 1: {0} Selection ID 2 {1} ähnelt.
        /// </summary>
        internal static string strSelectionIdMismatch {
            get {
                return ResourceManager.GetString("strSelectionIdMismatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Testing Mail Access Failed ähnelt.
        /// </summary>
        internal static string strTestMailFailedCaption {
            get {
                return ResourceManager.GetString("strTestMailFailedCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Testing of Mail settings succeeded. ähnelt.
        /// </summary>
        internal static string strTestMailSuccess {
            get {
                return ResourceManager.GetString("strTestMailSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Testing Mail Access Succeeded ähnelt.
        /// </summary>
        internal static string strTestMailSuccessCaption {
            get {
                return ResourceManager.GetString("strTestMailSuccessCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Added a Trade for Tipp at Race {0} Horse {1} at {2} ähnelt.
        /// </summary>
        internal static string strTradeAdded {
            get {
                return ResourceManager.GetString("strTradeAdded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Watcher ähnelt.
        /// </summary>
        internal static string strWatcher {
            get {
                return ResourceManager.GetString("strWatcher", resourceCulture);
            }
        }
    }
}
