//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.18444
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace net.sxtrader.bftradingstrategies.BFTSGUI {
    using System;
    
    
    /// <summary>
    ///   Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    /// </summary>
    // Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    // -Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    // Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    // mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class BFTSGUI {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal BFTSGUI() {
        }
        
        /// <summary>
        ///   Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("net.sxtrader.bftradingstrategies.BFTSGUI.BFTSGUI", typeof(BFTSGUI).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        ///   Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Your Beta-Registration Email: ähnelt.
        /// </summary>
        internal static string strBetaAddress {
            get {
                return ResourceManager.GetString("strBetaAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Email for Beta ähnelt.
        /// </summary>
        internal static string strBetaDialog {
            get {
                return ResourceManager.GetString("strBetaDialog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Check Betfair for bets every ähnelt.
        /// </summary>
        internal static string strBFCheck {
            get {
                return ResourceManager.GetString("strBFCheck", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die &amp;Apply ähnelt.
        /// </summary>
        internal static string strBtnApply {
            get {
                return ResourceManager.GetString("strBtnApply", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die &amp;Cancel ähnelt.
        /// </summary>
        internal static string strBtnCancel {
            get {
                return ResourceManager.GetString("strBtnCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die &amp;OK ähnelt.
        /// </summary>
        internal static string strBtnOK {
            get {
                return ResourceManager.GetString("strBtnOK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Configuration ähnelt.
        /// </summary>
        internal static string strConfiguration {
            get {
                return ResourceManager.GetString("strConfiguration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Confirm Fast Bets ähnelt.
        /// </summary>
        internal static string strConfirmFastBets {
            get {
                return ResourceManager.GetString("strConfirmFastBets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die &amp;Contact ähnelt.
        /// </summary>
        internal static string strContact {
            get {
                return ResourceManager.GetString("strContact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Report &amp;Bug ähnelt.
        /// </summary>
        internal static string strContactBug {
            get {
                return ResourceManager.GetString("strContactBug", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Make a &amp;Suggestion ähnelt.
        /// </summary>
        internal static string strContactSuggestion {
            get {
                return ResourceManager.GetString("strContactSuggestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die &amp;Donation ähnelt.
        /// </summary>
        internal static string strDonation {
            get {
                return ResourceManager.GetString("strDonation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die &amp;File ähnelt.
        /// </summary>
        internal static string strFile {
            get {
                return ResourceManager.GetString("strFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die &amp;Exit ähnelt.
        /// </summary>
        internal static string strFileExit {
            get {
                return ResourceManager.GetString("strFileExit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die General ähnelt.
        /// </summary>
        internal static string strGeneral {
            get {
                return ResourceManager.GetString("strGeneral", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die General Configuration ähnelt.
        /// </summary>
        internal static string strGeneralConfig {
            get {
                return ResourceManager.GetString("strGeneralConfig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die &amp;Help ähnelt.
        /// </summary>
        internal static string strHelp {
            get {
                return ResourceManager.GetString("strHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Check liveticker every ähnelt.
        /// </summary>
        internal static string strLiveTickerCheck {
            get {
                return ResourceManager.GetString("strLiveTickerCheck", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Log Bet Amounts ähnelt.
        /// </summary>
        internal static string strLogBetAmounts {
            get {
                return ResourceManager.GetString("strLogBetAmounts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Logging ähnelt.
        /// </summary>
        internal static string strLogging {
            get {
                return ResourceManager.GetString("strLogging", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Log Liveticker ähnelt.
        /// </summary>
        internal static string strLogLiveticker {
            get {
                return ResourceManager.GetString("strLogLiveticker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Log Trades ähnelt.
        /// </summary>
        internal static string strLogTrades {
            get {
                return ResourceManager.GetString("strLogTrades", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Remember me ähnelt.
        /// </summary>
        internal static string strRemember {
            get {
                return ResourceManager.GetString("strRemember", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die seconds ähnelt.
        /// </summary>
        internal static string strSeconds {
            get {
                return ResourceManager.GetString("strSeconds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die &amp;Tools ähnelt.
        /// </summary>
        internal static string strTools {
            get {
                return ResourceManager.GetString("strTools", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die &amp;Options ähnelt.
        /// </summary>
        internal static string strToolsOptions {
            get {
                return ResourceManager.GetString("strToolsOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Write debug information to file ähnelt.
        /// </summary>
        internal static string strWriteDebug {
            get {
                return ResourceManager.GetString("strWriteDebug", resourceCulture);
            }
        }
    }
}
