//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.34011
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace net.sxtrader.bftradingstrategies.common {
    using System;
    
    
    /// <summary>
    ///   Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    /// </summary>
    // Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    // -Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    // Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    // mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class HistoryGraph {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal HistoryGraph() {
        }
        
        /// <summary>
        ///   Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("net.sxtrader.bftradingstrategies.common.HistoryGraph", typeof(HistoryGraph).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        ///   Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Add Livescore ähnelt.
        /// </summary>
        internal static string strAddLivescore {
            get {
                return ResourceManager.GetString("strAddLivescore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die All ähnelt.
        /// </summary>
        internal static string strAll {
            get {
                return ResourceManager.GetString("strAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Avg 1st Goal Time ähnelt.
        /// </summary>
        internal static string strAvg1stGoalTime {
            get {
                return ResourceManager.GetString("strAvg1stGoalTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Average Goals ähnelt.
        /// </summary>
        internal static string strAvgGoals {
            get {
                return ResourceManager.GetString("strAvgGoals", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die age_of_data ähnelt.
        /// </summary>
        internal static string strCfgKeyAgeOfData {
            get {
                return ResourceManager.GetString("strCfgKeyAgeOfData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die colorOverUnderTrendOver ähnelt.
        /// </summary>
        internal static string strColorOUTrendOver {
            get {
                return ResourceManager.GetString("strColorOUTrendOver", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die colorOverUnderTrendUnder ähnelt.
        /// </summary>
        internal static string strColorOUTrendUnder {
            get {
                return ResourceManager.GetString("strColorOUTrendUnder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die colorWLDTrendDraw ähnelt.
        /// </summary>
        internal static string strColorWLDTrendDraw {
            get {
                return ResourceManager.GetString("strColorWLDTrendDraw", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die colorWLDTrendLoss ähnelt.
        /// </summary>
        internal static string strColorWLDTrendLoss {
            get {
                return ResourceManager.GetString("strColorWLDTrendLoss", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die colorWLDTrendWin ähnelt.
        /// </summary>
        internal static string strColorWLDTrendWin {
            get {
                return ResourceManager.GetString("strColorWLDTrendWin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die colorWLDTrendZero ähnelt.
        /// </summary>
        internal static string strColorWLDTrendZero {
            get {
                return ResourceManager.GetString("strColorWLDTrendZero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Date ähnelt.
        /// </summary>
        internal static string strDate {
            get {
                return ResourceManager.GetString("strDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Delete Livescore Mapping ähnelt.
        /// </summary>
        internal static string strDelLSCaption {
            get {
                return ResourceManager.GetString("strDelLSCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Are you sure that you want to delete the mapping {0}? ähnelt.
        /// </summary>
        internal static string strDelLSConfirm {
            get {
                return ResourceManager.GetString("strDelLSConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Delete this Livescore-Mapping ähnelt.
        /// </summary>
        internal static string strDelLSMapping {
            get {
                return ResourceManager.GetString("strDelLSMapping", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Show historical data ähnelt.
        /// </summary>
        internal static string strDescription {
            get {
                return ResourceManager.GetString("strDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Mappings between Livescore names and sport exchange names ähnelt.
        /// </summary>
        internal static string strDescriptionMapping {
            get {
                return ResourceManager.GetString("strDescriptionMapping", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Statistics and Analyses of todays inplay matches. ähnelt.
        /// </summary>
        internal static string strDescriptionSA {
            get {
                return ResourceManager.GetString("strDescriptionSA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Direct Confrontations ähnelt.
        /// </summary>
        internal static string strDirectConfrontations {
            get {
                return ResourceManager.GetString("strDirectConfrontations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Draw ähnelt.
        /// </summary>
        internal static string strDraw {
            get {
                return ResourceManager.GetString("strDraw", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Earliest 1st Goal time ähnelt.
        /// </summary>
        internal static string strEarliest1stGoalTime {
            get {
                return ResourceManager.GetString("strEarliest1stGoalTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die {0} Away ähnelt.
        /// </summary>
        internal static string strFormatAway {
            get {
                return ResourceManager.GetString("strFormatAway", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die {0} Home ähnelt.
        /// </summary>
        internal static string strFormatHome {
            get {
                return ResourceManager.GetString("strFormatHome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Common/Histogram ähnelt.
        /// </summary>
        internal static string strFQHistogramm {
            get {
                return ResourceManager.GetString("strFQHistogramm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Common/Livescore Mapping ähnelt.
        /// </summary>
        internal static string strFQMapper {
            get {
                return ResourceManager.GetString("strFQMapper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Common/Statistics &amp; Analyses ähnelt.
        /// </summary>
        internal static string strFQStatisticAnalyses {
            get {
                return ResourceManager.GetString("strFQStatisticAnalyses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Game Coloring ähnelt.
        /// </summary>
        internal static string strGameColor {
            get {
                return ResourceManager.GetString("strGameColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die General ähnelt.
        /// </summary>
        internal static string strGeneral {
            get {
                return ResourceManager.GetString("strGeneral", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Histogram ähnelt.
        /// </summary>
        internal static string strHistogramm {
            get {
                return ResourceManager.GetString("strHistogramm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Home/Away ähnelt.
        /// </summary>
        internal static string strHomeAway {
            get {
                return ResourceManager.GetString("strHomeAway", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Latest 1st Goal time ähnelt.
        /// </summary>
        internal static string strLatest1stGoalTime {
            get {
                return ResourceManager.GetString("strLatest1stGoalTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Loss ähnelt.
        /// </summary>
        internal static string strLoss {
            get {
                return ResourceManager.GetString("strLoss", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Livescore Mapping ähnelt.
        /// </summary>
        internal static string strMapper {
            get {
                return ResourceManager.GetString("strMapper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Money ähnelt.
        /// </summary>
        internal static string strMoney {
            get {
                return ResourceManager.GetString("strMoney", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die &amp;New Range ähnelt.
        /// </summary>
        internal static string strNewRange {
            get {
                return ResourceManager.GetString("strNewRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die no_of_data ähnelt.
        /// </summary>
        internal static string strNoOfData {
            get {
                return ResourceManager.GetString("strNoOfData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Opponents ähnelt.
        /// </summary>
        internal static string strOpponents {
            get {
                return ResourceManager.GetString("strOpponents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die ouOverPercentColor ähnelt.
        /// </summary>
        internal static string strOUOverPercentColor {
            get {
                return ResourceManager.GetString("strOUOverPercentColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die ouUnderPercentColor ähnelt.
        /// </summary>
        internal static string strOUUnderPercentColor {
            get {
                return ResourceManager.GetString("strOUUnderPercentColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Over ähnelt.
        /// </summary>
        internal static string strOver {
            get {
                return ResourceManager.GetString("strOver", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die scorecolorpercent ähnelt.
        /// </summary>
        internal static string strScoreColorPercent {
            get {
                return ResourceManager.GetString("strScoreColorPercent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Score Matrix ähnelt.
        /// </summary>
        internal static string strScoreMatrix {
            get {
                return ResourceManager.GetString("strScoreMatrix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die statcolor ähnelt.
        /// </summary>
        internal static string strStatColor {
            get {
                return ResourceManager.GetString("strStatColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die statcolors ähnelt.
        /// </summary>
        internal static string strStatColors {
            get {
                return ResourceManager.GetString("strStatColors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Statistics &amp; Analyses ähnelt.
        /// </summary>
        internal static string strStatisticAnalyses {
            get {
                return ResourceManager.GetString("strStatisticAnalyses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Statistic Server not availible. Please try again later. ähnelt.
        /// </summary>
        internal static string strStatisticServerNA {
            get {
                return ResourceManager.GetString("strStatisticServerNA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die {0} Historic Data ähnelt.
        /// </summary>
        internal static string strTeamHistDataFormat {
            get {
                return ResourceManager.GetString("strTeamHistDataFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Trend of last {0} matches: ähnelt.
        /// </summary>
        internal static string strTrendLabelFormat {
            get {
                return ResourceManager.GetString("strTrendLabelFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Under ähnelt.
        /// </summary>
        internal static string strUnder {
            get {
                return ResourceManager.GetString("strUnder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Win ähnelt.
        /// </summary>
        internal static string strWin {
            get {
                return ResourceManager.GetString("strWin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die wldDrawPercentColor ähnelt.
        /// </summary>
        internal static string strWLDDrawPercentColor {
            get {
                return ResourceManager.GetString("strWLDDrawPercentColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die wldLossPercentColor ähnelt.
        /// </summary>
        internal static string strWLDLossPercentColor {
            get {
                return ResourceManager.GetString("strWLDLossPercentColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die wldWinPercentColor ähnelt.
        /// </summary>
        internal static string strWLDWinPercentColor {
            get {
                return ResourceManager.GetString("strWLDWinPercentColor", resourceCulture);
            }
        }
    }
}
