//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.34011
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace net.sxtrader.bftradingstrategies.bfuestrategy {
    using System;
    
    
    /// <summary>
    ///   Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    /// </summary>
    // Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    // -Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    // Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    // mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class LayTheDraw {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal LayTheDraw() {
        }
        
        /// <summary>
        ///   Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("net.sxtrader.bftradingstrategies.bfuestrategy.LayTheDraw", typeof(LayTheDraw).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        ///   Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die check00nostopploss ähnelt.
        /// </summary>
        internal static string str00NoStoppLoss {
            get {
                return ResourceManager.GetString("str00NoStoppLoss", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die stopploss00percentage ähnelt.
        /// </summary>
        internal static string str00StopLossPercentage {
            get {
                return ResourceManager.GetString("str00StopLossPercentage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die win00percentage ähnelt.
        /// </summary>
        internal static string str00WinPercentage {
            get {
                return ResourceManager.GetString("str00WinPercentage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Activate Stop/Loss-Watch after ähnelt.
        /// </summary>
        internal static string strActivateStopLossWatch {
            get {
                return ResourceManager.GetString("strActivateStopLossWatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Match added. ähnelt.
        /// </summary>
        internal static string strAdded {
            get {
                return ResourceManager.GetString("strAdded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Add Liveticker ähnelt.
        /// </summary>
        internal static string strAddLivescore {
            get {
                return ResourceManager.GetString("strAddLivescore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die After goal was scored close trade after a waiting time of ähnelt.
        /// </summary>
        internal static string strAfterGoal {
            get {
                return ResourceManager.GetString("strAfterGoal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Always bet ähnelt.
        /// </summary>
        internal static string strAlwaysBet {
            get {
                return ResourceManager.GetString("strAlwaysBet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die and ähnelt.
        /// </summary>
        internal static string strAnd {
            get {
                return ResourceManager.GetString("strAnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Available Balance ähnelt.
        /// </summary>
        internal static string strAvailibleAmount {
            get {
                return ResourceManager.GetString("strAvailibleAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Available Livescores ähnelt.
        /// </summary>
        internal static string strAvailibleScores {
            get {
                return ResourceManager.GetString("strAvailibleScores", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Score is undraw and market odss are below the calculated value of {0} ähnelt.
        /// </summary>
        internal static string strBelowMinOdds {
            get {
                return ResourceManager.GetString("strBelowMinOdds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die BetAmount ähnelt.
        /// </summary>
        internal static string strBetAmount {
            get {
                return ResourceManager.GetString("strBetAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Market {0} Placed bet {1:C}@{2} ähnelt.
        /// </summary>
        internal static string strBetMatched {
            get {
                return ResourceManager.GetString("strBetMatched", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Market  {0} Placed unmatched bet {1:C}@{2} ähnelt.
        /// </summary>
        internal static string strBetUnmatched {
            get {
                return ResourceManager.GetString("strBetUnmatched", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Browse... ähnelt.
        /// </summary>
        internal static string strBrowse {
            get {
                return ResourceManager.GetString("strBrowse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die &amp;Delete ähnelt.
        /// </summary>
        internal static string strButtonDelete {
            get {
                return ResourceManager.GetString("strButtonDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die &amp;Edit ähnelt.
        /// </summary>
        internal static string strButtonEdit {
            get {
                return ResourceManager.GetString("strButtonEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die &amp;New ähnelt.
        /// </summary>
        internal static string strButtonNew {
            get {
                return ResourceManager.GetString("strButtonNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die &amp;Save ähnelt.
        /// </summary>
        internal static string strButtonSave {
            get {
                return ResourceManager.GetString("strButtonSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die &amp;Cancel ähnelt.
        /// </summary>
        internal static string strCancel {
            get {
                return ResourceManager.GetString("strCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Cancel bet ähnelt.
        /// </summary>
        internal static string strCancelBet {
            get {
                return ResourceManager.GetString("strCancelBet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die A Template File can&apos;t be created
        ///if there are no rules defined ähnelt.
        /// </summary>
        internal static string strCantCreateTemplate {
            get {
                return ResourceManager.GetString("strCantCreateTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die check00stopploss ähnelt.
        /// </summary>
        internal static string strCheck00StoppLoss {
            get {
                return ResourceManager.GetString("strCheck00StoppLoss", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die CheckExitOddsSeconds ähnelt.
        /// </summary>
        internal static string strCheckExitOddsSeconds {
            get {
                return ResourceManager.GetString("strCheckExitOddsSeconds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Check for Stop/Loss-Trade every  ähnelt.
        /// </summary>
        internal static string strCheckForStopLoss {
            get {
                return ResourceManager.GetString("strCheckForStopLoss", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die If Score is 0 - 0 and there&apos;s a Scoreline Trade and the Win on the 0 - 0 Market compared to
        /// the Loss on Draw Market isthe Loss on Draw Market is ähnelt.
        /// </summary>
        internal static string strCheckScoreline00Cfg {
            get {
                return ResourceManager.GetString("strCheckScoreline00Cfg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die CheckServerBetsSeconds ähnelt.
        /// </summary>
        internal static string strCheckServerBetsSeconds {
            get {
                return ResourceManager.GetString("strCheckServerBetsSeconds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Check for Stop/Loss Odds every ähnelt.
        /// </summary>
        internal static string strCheckStopLossOdds {
            get {
                return ResourceManager.GetString("strCheckStopLossOdds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Configuration Lay The Draw ähnelt.
        /// </summary>
        internal static string strConfigurationLTD {
            get {
                return ResourceManager.GetString("strConfigurationLTD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Do you really want to place a Lay bet of {0} {1} for the odds of {2}? ähnelt.
        /// </summary>
        internal static string strConfirmFastBet {
            get {
                return ResourceManager.GetString("strConfirmFastBet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Connect ähnelt.
        /// </summary>
        internal static string strConnect {
            get {
                return ResourceManager.GetString("strConnect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Strategy is activated at program start? ähnelt.
        /// </summary>
        internal static string strDefaultActivation {
            get {
                return ResourceManager.GetString("strDefaultActivation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Lays the Draw and Backs it after a goal was scored ähnelt.
        /// </summary>
        internal static string strDescription {
            get {
                return ResourceManager.GetString("strDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Disconnect Livescore {0} ähnelt.
        /// </summary>
        internal static string strDisCLivescore {
            get {
                return ResourceManager.GetString("strDisCLivescore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Score is draw and odd is less than {0}. Leaving ähnelt.
        /// </summary>
        internal static string strDontCloseDrawOddsMessage {
            get {
                return ResourceManager.GetString("strDontCloseDrawOddsMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die DontCloseDrawPlaytime ähnelt.
        /// </summary>
        internal static string strDontCloseDrawPlaytime {
            get {
                return ResourceManager.GetString("strDontCloseDrawPlaytime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Don&apos;t Close Trade when score is draw and playtime is lower than ähnelt.
        /// </summary>
        internal static string strDontCloseDrawPlaytimeLabel {
            get {
                return ResourceManager.GetString("strDontCloseDrawPlaytimeLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Score is draw and playtime is less than {0}. Leaving ähnelt.
        /// </summary>
        internal static string strDontCloseDrawPlaytimeMessage {
            get {
                return ResourceManager.GetString("strDontCloseDrawPlaytimeMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die DontCloseOdds ähnelt.
        /// </summary>
        internal static string strDontCloseOdds {
            get {
                return ResourceManager.GetString("strDontCloseOdds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die DontCloseRetrySeconds ähnelt.
        /// </summary>
        internal static string strDontCloseRetrySeconds {
            get {
                return ResourceManager.GetString("strDontCloseRetrySeconds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Don&apos;t close when there&apos;s a undraw and bet differ minus  ähnelt.
        /// </summary>
        internal static string strDontCloseTrade {
            get {
                return ResourceManager.GetString("strDontCloseTrade", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Equal Red Cards ähnelt.
        /// </summary>
        internal static string strEqualRedCards {
            get {
                return ResourceManager.GetString("strEqualRedCards", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Error saving Template ähnelt.
        /// </summary>
        internal static string strErrorSaveTemplate {
            get {
                return ResourceManager.GetString("strErrorSaveTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die ExitCloseOdds ähnelt.
        /// </summary>
        internal static string strExitCloseOdds {
            get {
                return ResourceManager.GetString("strExitCloseOdds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die ExitWatchActivationPlaytime ähnelt.
        /// </summary>
        internal static string strExitWatchActivationPlaytime {
            get {
                return ResourceManager.GetString("strExitWatchActivationPlaytime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die FastBetFixedAmountValue ähnelt.
        /// </summary>
        internal static string strFastBetFixedAmountValue {
            get {
                return ResourceManager.GetString("strFastBetFixedAmountValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die FastBetPercentAmountValue ähnelt.
        /// </summary>
        internal static string strFastBetPercentAmountValue {
            get {
                return ResourceManager.GetString("strFastBetPercentAmountValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die FastBetPercentTotalAmount ähnelt.
        /// </summary>
        internal static string strFastBetPercentTotalAmount {
            get {
                return ResourceManager.GetString("strFastBetPercentTotalAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Unmatched/Partly matched behaviour ähnelt.
        /// </summary>
        internal static string strFastBetUnmatchBehaviourLabel {
            get {
                return ResourceManager.GetString("strFastBetUnmatchBehaviourLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die FastBetUnmatchedCancel ähnelt.
        /// </summary>
        internal static string strFastBetUnmatchedCancel {
            get {
                return ResourceManager.GetString("strFastBetUnmatchedCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die FastBetUnmatchedWaitSeconds ähnelt.
        /// </summary>
        internal static string strFastBetUnmatchedWaitSeconds {
            get {
                return ResourceManager.GetString("strFastBetUnmatchedWaitSeconds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Fast Lay ähnelt.
        /// </summary>
        internal static string strFastLay {
            get {
                return ResourceManager.GetString("strFastLay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die FastLayFixedAmount ähnelt.
        /// </summary>
        internal static string strFastLayFixedAmount {
            get {
                return ResourceManager.GetString("strFastLayFixedAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die FileGameEndedSound ähnelt.
        /// </summary>
        internal static string strFileGameEndedSound {
            get {
                return ResourceManager.GetString("strFileGameEndedSound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die FileMatchAddedSound ähnelt.
        /// </summary>
        internal static string strFileMatchAddedSound {
            get {
                return ResourceManager.GetString("strFileMatchAddedSound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die FileScoreChangedSound ähnelt.
        /// </summary>
        internal static string strFileScoreChangedSound {
            get {
                return ResourceManager.GetString("strFileScoreChangedSound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die FileTradingChangedSound ähnelt.
        /// </summary>
        internal static string strFileTradingChangedSound {
            get {
                return ResourceManager.GetString("strFileTradingChangedSound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Soccer/Lay The Draw ähnelt.
        /// </summary>
        internal static string strFQLayTheDraw {
            get {
                return ResourceManager.GetString("strFQLayTheDraw", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Game Behavior ähnelt.
        /// </summary>
        internal static string strGameBehavior {
            get {
                return ResourceManager.GetString("strGameBehavior", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Game Ended ähnelt.
        /// </summary>
        internal static string strGameEnded {
            get {
                return ResourceManager.GetString("strGameEnded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Behaviour General ähnelt.
        /// </summary>
        internal static string strGeneralBehaviour {
            get {
                return ResourceManager.GetString("strGeneralBehaviour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Behaviour Goal Scored ähnelt.
        /// </summary>
        internal static string strGoalScoredBehaviour {
            get {
                return ResourceManager.GetString("strGoalScoredBehaviour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die GoalScoredCloseTradeSeconds ähnelt.
        /// </summary>
        internal static string strGoalScoredCloseTradeSeconds {
            get {
                return ResourceManager.GetString("strGoalScoredCloseTradeSeconds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Livescore 1 ähnelt.
        /// </summary>
        internal static string strLivescore1 {
            get {
                return ResourceManager.GetString("strLivescore1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Livescore 2 ähnelt.
        /// </summary>
        internal static string strLivescore2 {
            get {
                return ResourceManager.GetString("strLivescore2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Livescore Matches ähnelt.
        /// </summary>
        internal static string strLivescoreMatches {
            get {
                return ResourceManager.GetString("strLivescoreMatches", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Local Configuration for Single Match ähnelt.
        /// </summary>
        internal static string strLocalConfig {
            get {
                return ResourceManager.GetString("strLocalConfig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die You have to chose a match! If you don&apos;t want to connect this match to a Liveticker then please chose the Match Team None - Team None. ähnelt.
        /// </summary>
        internal static string strManualConnectionAdvise {
            get {
                return ResourceManager.GetString("strManualConnectionAdvise", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The Betfair Match {0} was manually linked with Livescore Match {1} ähnelt.
        /// </summary>
        internal static string strManuallyAdded {
            get {
                return ResourceManager.GetString("strManuallyAdded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Market is already settled. ähnelt.
        /// </summary>
        internal static string strMarketSettled {
            get {
                return ResourceManager.GetString("strMarketSettled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Market is suspended. Retrying. ähnelt.
        /// </summary>
        internal static string strMarketSuspended {
            get {
                return ResourceManager.GetString("strMarketSuspended", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Market Volume between ähnelt.
        /// </summary>
        internal static string strMarketVolumeBetween {
            get {
                return ResourceManager.GetString("strMarketVolumeBetween", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The upper end of the market volume interval must be greater than the lower end! ähnelt.
        /// </summary>
        internal static string strMarketVolumeHighLowMismatch {
            get {
                return ResourceManager.GetString("strMarketVolumeHighLowMismatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Match Added ähnelt.
        /// </summary>
        internal static string strMatchAdded {
            get {
                return ResourceManager.GetString("strMatchAdded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Match not found! ähnelt.
        /// </summary>
        internal static string strMatchNotFound {
            get {
                return ResourceManager.GetString("strMatchNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Lay The Draw ähnelt.
        /// </summary>
        internal static string strModule {
            get {
                return ResourceManager.GetString("strModule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Lay The Draw ähnelt.
        /// </summary>
        internal static string strName {
            get {
                return ResourceManager.GetString("strName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die No ähnelt.
        /// </summary>
        internal static string strNo {
            get {
                return ResourceManager.GetString("strNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die NoCloseTradeDrawOdds ähnelt.
        /// </summary>
        internal static string strNoCloseTradeDrawOdds {
            get {
                return ResourceManager.GetString("strNoCloseTradeDrawOdds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die No Liveticker ähnelt.
        /// </summary>
        internal static string strNoLivescore {
            get {
                return ResourceManager.GetString("strNoLivescore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die No market info. Retrying. ähnelt.
        /// </summary>
        internal static string strNoMarketInfo {
            get {
                return ResourceManager.GetString("strNoMarketInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die No market prices. Retrying. ähnelt.
        /// </summary>
        internal static string strNoMarketPrices {
            get {
                return ResourceManager.GetString("strNoMarketPrices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The match is already Inplay. No more preplay target bet possible ähnelt.
        /// </summary>
        internal static string strNoMorePreplayTargetBet {
            get {
                return ResourceManager.GetString("strNoMorePreplayTargetBet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die No Parameter was provided in Module {0} ähnelt.
        /// </summary>
        internal static string strNoParameter {
            get {
                return ResourceManager.GetString("strNoParameter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die No Red Cards ähnelt.
        /// </summary>
        internal static string strNoRedCards {
            get {
                return ResourceManager.GetString("strNoRedCards", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die No Stop/Loss because Close-Trade is running. ähnelt.
        /// </summary>
        internal static string strNoStopLossRun {
            get {
                return ResourceManager.GetString("strNoStopLossRun", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die NoStoppLossOdds ähnelt.
        /// </summary>
        internal static string strNoStoppLossOdds {
            get {
                return ResourceManager.GetString("strNoStoppLossOdds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Observe Red Cards ähnelt.
        /// </summary>
        internal static string strObserveRedCards {
            get {
                return ResourceManager.GetString("strObserveRedCards", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Odds ähnelt.
        /// </summary>
        internal static string strOdds {
            get {
                return ResourceManager.GetString("strOdds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Current Odds are higher than expected odds of {0}. Retrying. ähnelt.
        /// </summary>
        internal static string strOdds2HighForStopLoss {
            get {
                return ResourceManager.GetString("strOdds2HighForStopLoss", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Odds between ähnelt.
        /// </summary>
        internal static string strOddsBetween {
            get {
                return ResourceManager.GetString("strOddsBetween", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The upper end of the odd interval must be greater than the lower end! ähnelt.
        /// </summary>
        internal static string strOddsHighLowMismatch {
            get {
                return ResourceManager.GetString("strOddsHighLowMismatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die &amp;OK ähnelt.
        /// </summary>
        internal static string strOK {
            get {
                return ResourceManager.GetString("strOK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die There was an error while opening file {0} ähnelt.
        /// </summary>
        internal static string strOpenFileError {
            get {
                return ResourceManager.GetString("strOpenFileError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Open Trade if there is a settled market ähnelt.
        /// </summary>
        internal static string strOpenTradeSettled {
            get {
                return ResourceManager.GetString("strOpenTradeSettled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Open Trade if there is a unsettled market ähnelt.
        /// </summary>
        internal static string strOpenTradeUnsettled {
            get {
                return ResourceManager.GetString("strOpenTradeUnsettled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die % of ähnelt.
        /// </summary>
        internal static string strPercentOf {
            get {
                return ResourceManager.GetString("strPercentOf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die % of initial Bet ähnelt.
        /// </summary>
        internal static string strPercentStopLoss {
            get {
                return ResourceManager.GetString("strPercentStopLoss", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Place Back-Bet for Market {0} with Odds {1} for {2} € ähnelt.
        /// </summary>
        internal static string strPlaceBet {
            get {
                return ResourceManager.GetString("strPlaceBet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Play ähnelt.
        /// </summary>
        internal static string strPlay {
            get {
                return ResourceManager.GetString("strPlay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die PlayMatchEndedSound ähnelt.
        /// </summary>
        internal static string strPlayGameEndedSound {
            get {
                return ResourceManager.GetString("strPlayGameEndedSound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die PlayMatchAddedSound ähnelt.
        /// </summary>
        internal static string strPlayMatchAddedSound {
            get {
                return ResourceManager.GetString("strPlayMatchAddedSound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die PlayScoreChangedSound ähnelt.
        /// </summary>
        internal static string strPlayScoreChangedSound {
            get {
                return ResourceManager.GetString("strPlayScoreChangedSound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Play Sounds ähnelt.
        /// </summary>
        internal static string strPlaySounds {
            get {
                return ResourceManager.GetString("strPlaySounds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Play Sounds ähnelt.
        /// </summary>
        internal static string strPlaySoundsText {
            get {
                return ResourceManager.GetString("strPlaySoundsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Playtime between ähnelt.
        /// </summary>
        internal static string strPlaytimeBetween {
            get {
                return ResourceManager.GetString("strPlaytimeBetween", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The upper end of the playtime interval must be greater than the lower end! ähnelt.
        /// </summary>
        internal static string strPlayTimeHighLowMismatch {
            get {
                return ResourceManager.GetString("strPlayTimeHighLowMismatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Minutes of Playtime ähnelt.
        /// </summary>
        internal static string strPlaytimeMinute {
            get {
                return ResourceManager.GetString("strPlaytimeMinute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die PlayTradingChangedSound ähnelt.
        /// </summary>
        internal static string strPlayTradingChangedSound {
            get {
                return ResourceManager.GetString("strPlayTradingChangedSound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Plugin {0} was activated ähnelt.
        /// </summary>
        internal static string strPluginActivated {
            get {
                return ResourceManager.GetString("strPluginActivated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Plugin {0} was deactivated ähnelt.
        /// </summary>
        internal static string strPluginDeactivated {
            get {
                return ResourceManager.GetString("strPluginDeactivated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Plugin {0} loaded ähnelt.
        /// </summary>
        internal static string strPluginLoaded {
            get {
                return ResourceManager.GetString("strPluginLoaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Preplay Target Bet Error ähnelt.
        /// </summary>
        internal static string strPreplayTargetError {
            get {
                return ResourceManager.GetString("strPreplayTargetError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Red Card Behaviour ähnelt.
        /// </summary>
        internal static string strRedCardBehaviour {
            get {
                return ResourceManager.GetString("strRedCardBehaviour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Score ähnelt.
        /// </summary>
        internal static string strScore {
            get {
                return ResourceManager.GetString("strScore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Score Changed ähnelt.
        /// </summary>
        internal static string strScoreChanged {
            get {
                return ResourceManager.GetString("strScoreChanged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Scoreline 0 - 0 ähnelt.
        /// </summary>
        internal static string strScoreline00 {
            get {
                return ResourceManager.GetString("strScoreline00", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Seconds ähnelt.
        /// </summary>
        internal static string strSeconds {
            get {
                return ResourceManager.GetString("strSeconds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Check server for new bets every  ähnelt.
        /// </summary>
        internal static string strServerCheck {
            get {
                return ResourceManager.GetString("strServerCheck", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die No Stop/Loss ähnelt.
        /// </summary>
        internal static string strSL00NoStopLoss {
            get {
                return ResourceManager.GetString("strSL00NoStopLoss", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Place Stop/Loss for ähnelt.
        /// </summary>
        internal static string strSL00StopLoss {
            get {
                return ResourceManager.GetString("strSL00StopLoss", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Sound ähnelt.
        /// </summary>
        internal static string strSound {
            get {
                return ResourceManager.GetString("strSound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Behaviour Stop/Loss ähnelt.
        /// </summary>
        internal static string strStopLossBehaviour {
            get {
                return ResourceManager.GetString("strStopLossBehaviour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Start Stop/Loss-Trade when Odds are lower than ähnelt.
        /// </summary>
        internal static string strStopLossTrade {
            get {
                return ResourceManager.GetString("strStopLossTrade", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die StrategyActivated ähnelt.
        /// </summary>
        internal static string strStrategyActivated {
            get {
                return ResourceManager.GetString("strStrategyActivated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Strategy Active ähnelt.
        /// </summary>
        internal static string strStrategyActive {
            get {
                return ResourceManager.GetString("strStrategyActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Match already ended. No betting possible anymore. ähnelt.
        /// </summary>
        internal static string strTargetBetMatchEnded {
            get {
                return ResourceManager.GetString("strTargetBetMatchEnded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Place Lay with Odds of ähnelt.
        /// </summary>
        internal static string strTargetOdds {
            get {
                return ResourceManager.GetString("strTargetOdds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Team A more Red Cards ähnelt.
        /// </summary>
        internal static string strTeamAMoreRedCards {
            get {
                return ResourceManager.GetString("strTeamAMoreRedCards", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Team B more Red Cards ähnelt.
        /// </summary>
        internal static string strTeamBMoreRedCards {
            get {
                return ResourceManager.GetString("strTeamBMoreRedCards", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die There was an error while deleting the existing template file ähnelt.
        /// </summary>
        internal static string strTemplateErrorDelete {
            get {
                return ResourceManager.GetString("strTemplateErrorDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Template File has no identification ähnelt.
        /// </summary>
        internal static string strTemplateErrorNoId {
            get {
                return ResourceManager.GetString("strTemplateErrorNoId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Template File is not a Lay The Draw Template ähnelt.
        /// </summary>
        internal static string strTemplateErrorNoLTD {
            get {
                return ResourceManager.GetString("strTemplateErrorNoLTD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die There was an unexpected error while opening file ähnelt.
        /// </summary>
        internal static string strTemplateErrorUnexpected {
            get {
                return ResourceManager.GetString("strTemplateErrorUnexpected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Error while loading Template ähnelt.
        /// </summary>
        internal static string strTemplateLoadeError {
            get {
                return ResourceManager.GetString("strTemplateLoadeError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Save Template ähnelt.
        /// </summary>
        internal static string strTemplateSave {
            get {
                return ResourceManager.GetString("strTemplateSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die There was an unexpected error while saving file ähnelt.
        /// </summary>
        internal static string strTemplateSaveErrorUnexpected {
            get {
                return ResourceManager.GetString("strTemplateSaveErrorUnexpected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Successfully saved template:
        ///{0} ähnelt.
        /// </summary>
        internal static string strTemplateSaveSuccess {
            get {
                return ResourceManager.GetString("strTemplateSaveSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Ticks from initial bet. ähnelt.
        /// </summary>
        internal static string strTicksBet {
            get {
                return ResourceManager.GetString("strTicksBet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Manual Livescore Connection ähnelt.
        /// </summary>
        internal static string strTitle {
            get {
                return ResourceManager.GetString("strTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Total Balance ähnelt.
        /// </summary>
        internal static string strTotalAmount {
            get {
                return ResourceManager.GetString("strTotalAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Cancel unmatched trade-close-bet and rebet after  ähnelt.
        /// </summary>
        internal static string strTradeCloseUnmatched {
            get {
                return ResourceManager.GetString("strTradeCloseUnmatched", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die If no Trade was placed wait for retry ähnelt.
        /// </summary>
        internal static string strTradeCloseWait {
            get {
                return ResourceManager.GetString("strTradeCloseWait", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Trade Configuration ähnelt.
        /// </summary>
        internal static string strTradeConfig {
            get {
                return ResourceManager.GetString("strTradeConfig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Trading Changed ähnelt.
        /// </summary>
        internal static string strTradingChanged {
            get {
                return ResourceManager.GetString("strTradingChanged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die UnmatchedWaitSeconds ähnelt.
        /// </summary>
        internal static string strUnmatchedWaitSeconds {
            get {
                return ResourceManager.GetString("strUnmatchedWaitSeconds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Wait ähnelt.
        /// </summary>
        internal static string strWait {
            get {
                return ResourceManager.GetString("strWait", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Too many or too less parameters provided in Module {0} ähnelt.
        /// </summary>
        internal static string strWrongParameterCount {
            get {
                return ResourceManager.GetString("strWrongParameterCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Parameter {0}: Wrong Parametertype. Expected Parametertype {1} ähnelt.
        /// </summary>
        internal static string strWrongParameterType {
            get {
                return ResourceManager.GetString("strWrongParameterType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Yes ähnelt.
        /// </summary>
        internal static string strYes {
            get {
                return ResourceManager.GetString("strYes", resourceCulture);
            }
        }
    }
}
