//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.18052
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace net.sxtrader.bftradingstrategies.LayThe4 {
    using System;
    
    
    /// <summary>
    ///   Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    /// </summary>
    // Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    // -Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    // Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    // mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class LayThe4 {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal LayThe4() {
        }
        
        /// <summary>
        ///   Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("net.sxtrader.bftradingstrategies.LayThe4.LayThe4", typeof(LayThe4).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        ///   Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Active ähnelt.
        /// </summary>
        internal static string strActive {
            get {
                return ResourceManager.GetString("strActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Add Livescore ähnelt.
        /// </summary>
        internal static string strAddLivescore {
            get {
                return ResourceManager.GetString("strAddLivescore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die After ähnelt.
        /// </summary>
        internal static string strAfter {
            get {
                return ResourceManager.GetString("strAfter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die and ähnelt.
        /// </summary>
        internal static string strAnd {
            get {
                return ResourceManager.GetString("strAnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Automatic start a trade when the odds are between ähnelt.
        /// </summary>
        internal static string strAutoOdds {
            get {
                return ResourceManager.GetString("strAutoOdds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Automatic Trade ähnelt.
        /// </summary>
        internal static string strAutoTrade {
            get {
                return ResourceManager.GetString("strAutoTrade", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Automatic Trading? ähnelt.
        /// </summary>
        internal static string strAutoTradeQ {
            get {
                return ResourceManager.GetString("strAutoTradeQ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Calculated money {0} is lower than allowed minimal stake of Betfair. The allowed minimal stake is {1} ähnelt.
        /// </summary>
        internal static string strBelowMinStake {
            get {
                return ResourceManager.GetString("strBelowMinStake", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Dispose a lower amount of bank ähnelt.
        /// </summary>
        internal static string strBetLower {
            get {
                return ResourceManager.GetString("strBetLower", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Browse... ähnelt.
        /// </summary>
        internal static string strBrowse {
            get {
                return ResourceManager.GetString("strBrowse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die &amp;Cancel ähnelt.
        /// </summary>
        internal static string strCancel {
            get {
                return ResourceManager.GetString("strCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Close trade ähnelt.
        /// </summary>
        internal static string strCloseTrade {
            get {
                return ResourceManager.GetString("strCloseTrade", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Configuration Lay The 4 ähnelt.
        /// </summary>
        internal static string strConfigLT4 {
            get {
                return ResourceManager.GetString("strConfigLT4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Strategy is activated at program start? ähnelt.
        /// </summary>
        internal static string strDefaultActivation {
            get {
                return ResourceManager.GetString("strDefaultActivation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Don&apos;t start a trade ähnelt.
        /// </summary>
        internal static string strDontPlace {
            get {
                return ResourceManager.GetString("strDontPlace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die FileGameEndedSound ähnelt.
        /// </summary>
        internal static string strFileGameEndedSound {
            get {
                return ResourceManager.GetString("strFileGameEndedSound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die FileMatchAddedSound ähnelt.
        /// </summary>
        internal static string strFileMatchAddedSound {
            get {
                return ResourceManager.GetString("strFileMatchAddedSound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die FileScoreChangedSound ähnelt.
        /// </summary>
        internal static string strFileScoreChangedSound {
            get {
                return ResourceManager.GetString("strFileScoreChangedSound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die FileTradingChangedSound ähnelt.
        /// </summary>
        internal static string strFileTradingChangedSound {
            get {
                return ResourceManager.GetString("strFileTradingChangedSound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Soccer/Lay The 4 ähnelt.
        /// </summary>
        internal static string strFQLayThe4 {
            get {
                return ResourceManager.GetString("strFQLayThe4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Game Ended ähnelt.
        /// </summary>
        internal static string strGameEnded {
            get {
                return ResourceManager.GetString("strGameEnded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die goal(s) wait ähnelt.
        /// </summary>
        internal static string strGoalWait {
            get {
                return ResourceManager.GetString("strGoalWait", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Lay-odds are lower than {0} or higher than {1} ähnelt.
        /// </summary>
        internal static string strLayOddsOutOfRange {
            get {
                return ResourceManager.GetString("strLayOddsOutOfRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Lay The 4 ähnelt.
        /// </summary>
        internal static string strLayThe4 {
            get {
                return ResourceManager.GetString("strLayThe4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Lay the Total Goals of 4  and Back it after defined time. ähnelt.
        /// </summary>
        internal static string strLayThe4Descr {
            get {
                return ResourceManager.GetString("strLayThe4Descr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Lay-Bet was not matched; ähnelt.
        /// </summary>
        internal static string strLayUnmatched {
            get {
                return ResourceManager.GetString("strLayUnmatched", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Livescore 1 ähnelt.
        /// </summary>
        internal static string strLivescore1 {
            get {
                return ResourceManager.GetString("strLivescore1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Livescore 2 ähnelt.
        /// </summary>
        internal static string strLivescore2 {
            get {
                return ResourceManager.GetString("strLivescore2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Local Configuration for Single Match ähnelt.
        /// </summary>
        internal static string strLocalConfig {
            get {
                return ResourceManager.GetString("strLocalConfig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Only trade on markets where the volume of market is higher than ähnelt.
        /// </summary>
        internal static string strMarkets {
            get {
                return ResourceManager.GetString("strMarkets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Match Added ähnelt.
        /// </summary>
        internal static string strMatchAdded {
            get {
                return ResourceManager.GetString("strMatchAdded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die and a maximum of ähnelt.
        /// </summary>
        internal static string strMaximum {
            get {
                return ResourceManager.GetString("strMaximum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die But a minimum of ähnelt.
        /// </summary>
        internal static string strMinimum {
            get {
                return ResourceManager.GetString("strMinimum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Minutes ähnelt.
        /// </summary>
        internal static string strMinutes {
            get {
                return ResourceManager.GetString("strMinutes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die minute of playtime ähnelt.
        /// </summary>
        internal static string strMinutesOfPlaytime {
            get {
                return ResourceManager.GetString("strMinutesOfPlaytime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Lay The 4 ähnelt.
        /// </summary>
        internal static string strModule {
            get {
                return ResourceManager.GetString("strModule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die No lay-odds for market. ähnelt.
        /// </summary>
        internal static string strNoLayOdds {
            get {
                return ResourceManager.GetString("strNoLayOdds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die No Livescore ähnelt.
        /// </summary>
        internal static string strNoLivescore {
            get {
                return ResourceManager.GetString("strNoLivescore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die There was no mapping found between this match and the liveticker ähnelt.
        /// </summary>
        internal static string strNoLVMap {
            get {
                return ResourceManager.GetString("strNoLVMap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Volume of market is too low. ähnelt.
        /// </summary>
        internal static string strNoMarketVolume {
            get {
                return ResourceManager.GetString("strNoMarketVolume", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Calculated money {0} to place is lower than customized minimal to place of {1} ähnelt.
        /// </summary>
        internal static string strNoMoneyAvailible {
            get {
                return ResourceManager.GetString("strNoMoneyAvailible", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die No Parameter was provided in Module {0} ähnelt.
        /// </summary>
        internal static string strNoParameter {
            get {
                return ResourceManager.GetString("strNoParameter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die If there&apos;s no profit ähnelt.
        /// </summary>
        internal static string strNoProfit {
            get {
                return ResourceManager.GetString("strNoProfit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die % of bank. ähnelt.
        /// </summary>
        internal static string strOfBank {
            get {
                return ResourceManager.GetString("strOfBank", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die &amp;OK ähnelt.
        /// </summary>
        internal static string strOK {
            get {
                return ResourceManager.GetString("strOK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Passive ähnelt.
        /// </summary>
        internal static string strPassive {
            get {
                return ResourceManager.GetString("strPassive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Always place ähnelt.
        /// </summary>
        internal static string strPlace {
            get {
                return ResourceManager.GetString("strPlace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Place Back-Bet for Market {0} with Odds {1} for {2} € ähnelt.
        /// </summary>
        internal static string strPlaceBet {
            get {
                return ResourceManager.GetString("strPlaceBet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Play ähnelt.
        /// </summary>
        internal static string strPlay {
            get {
                return ResourceManager.GetString("strPlay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die PlayMatchEndedSound ähnelt.
        /// </summary>
        internal static string strPlayGameEndedSound {
            get {
                return ResourceManager.GetString("strPlayGameEndedSound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die PlayMatchAddedSound ähnelt.
        /// </summary>
        internal static string strPlayMatchAddedSound {
            get {
                return ResourceManager.GetString("strPlayMatchAddedSound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die PlayScoreChangedSound ähnelt.
        /// </summary>
        internal static string strPlayScoreChangedSound {
            get {
                return ResourceManager.GetString("strPlayScoreChangedSound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Play Sounds ähnelt.
        /// </summary>
        internal static string strPlaySounds {
            get {
                return ResourceManager.GetString("strPlaySounds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Play Sounds ähnelt.
        /// </summary>
        internal static string strPlaySounds1 {
            get {
                return ResourceManager.GetString("strPlaySounds1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Play Sounds ähnelt.
        /// </summary>
        internal static string strPlaySoundsText {
            get {
                return ResourceManager.GetString("strPlaySoundsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Play Sounds ähnelt.
        /// </summary>
        internal static string strPlaySoundsText1 {
            get {
                return ResourceManager.GetString("strPlaySoundsText1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Minutes of Playtime ähnelt.
        /// </summary>
        internal static string strPlaytimeMinute {
            get {
                return ResourceManager.GetString("strPlaytimeMinute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die PlayTradingChangedSound ähnelt.
        /// </summary>
        internal static string strPlayTradingChangedSound {
            get {
                return ResourceManager.GetString("strPlayTradingChangedSound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Plugin {0} loaded ähnelt.
        /// </summary>
        internal static string strPluginLoaded {
            get {
                return ResourceManager.GetString("strPluginLoaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die If there&apos;s profit ähnelt.
        /// </summary>
        internal static string strProfit {
            get {
                return ResourceManager.GetString("strProfit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die If profit is lower than ähnelt.
        /// </summary>
        internal static string strProfitLower {
            get {
                return ResourceManager.GetString("strProfitLower", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die % then wait ähnelt.
        /// </summary>
        internal static string strProfitWait {
            get {
                return ResourceManager.GetString("strProfitWait", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Score Changed ähnelt.
        /// </summary>
        internal static string strScoreChanged {
            get {
                return ResourceManager.GetString("strScoreChanged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die seconds ähnelt.
        /// </summary>
        internal static string strSeconds {
            get {
                return ResourceManager.GetString("strSeconds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die seconds and close trade ähnelt.
        /// </summary>
        internal static string strSecondsCloseTrades {
            get {
                return ResourceManager.GetString("strSecondsCloseTrades", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die seconds before market goes In-Play ähnelt.
        /// </summary>
        internal static string strSecondsMarketInplay {
            get {
                return ResourceManager.GetString("strSecondsMarketInplay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Check server for new bets every ähnelt.
        /// </summary>
        internal static string strServerCheck {
            get {
                return ResourceManager.GetString("strServerCheck", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Start Close-Trade-Watch after ähnelt.
        /// </summary>
        internal static string strStartExitWatch {
            get {
                return ResourceManager.GetString("strStartExitWatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Strategy Controlling ähnelt.
        /// </summary>
        internal static string strStrategyContrl {
            get {
                return ResourceManager.GetString("strStrategyContrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die If disposable amount of bank is too low for lay ähnelt.
        /// </summary>
        internal static string strTooLow {
            get {
                return ResourceManager.GetString("strTooLow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Trade added and started ähnelt.
        /// </summary>
        internal static string strTradedAddedAndStarted {
            get {
                return ResourceManager.GetString("strTradedAddedAndStarted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Start trade ähnelt.
        /// </summary>
        internal static string strTradeStart {
            get {
                return ResourceManager.GetString("strTradeStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Trading Changed ähnelt.
        /// </summary>
        internal static string strTradingChanged {
            get {
                return ResourceManager.GetString("strTradingChanged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Wait ähnelt.
        /// </summary>
        internal static string strWait {
            get {
                return ResourceManager.GetString("strWait", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Too many or too less parameters provided in Module {0} ähnelt.
        /// </summary>
        internal static string strWrongParameterCount {
            get {
                return ResourceManager.GetString("strWrongParameterCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Parameter {0}: Wrong Parametertype. Expected Parametertype {1} ähnelt.
        /// </summary>
        internal static string strWrongParameterType {
            get {
                return ResourceManager.GetString("strWrongParameterType", resourceCulture);
            }
        }
    }
}
