//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.34011
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace net.sxtrader.bftradingstrategies.ttr {
    using System;
    
    
    /// <summary>
    ///   Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    /// </summary>
    // Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    // -Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    // Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    // mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class TradeTheReaction {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal TradeTheReaction() {
        }
        
        /// <summary>
        ///   Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("net.sxtrader.bftradingstrategies.ttr.TradeTheReaction", typeof(TradeTheReaction).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        ///   Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die and  ähnelt.
        /// </summary>
        internal static string strAnd {
            get {
                return ResourceManager.GetString("strAnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Always calculate so that Liability/Win is ähnelt.
        /// </summary>
        internal static string strASBetAmountByTarget {
            get {
                return ResourceManager.GetString("strASBetAmountByTarget", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Trade Type: ähnelt.
        /// </summary>
        internal static string strASCETradeTypeCbx {
            get {
                return ResourceManager.GetString("strASCETradeTypeCbx", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die &amp;Delete ähnelt.
        /// </summary>
        internal static string strASDisplayDeleteBtn {
            get {
                return ResourceManager.GetString("strASDisplayDeleteBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die &amp;Edit ähnelt.
        /// </summary>
        internal static string strASDisplayEditBtn {
            get {
                return ResourceManager.GetString("strASDisplayEditBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die and ähnelt.
        /// </summary>
        internal static string strASLS00AndLbl {
            get {
                return ResourceManager.GetString("strASLS00AndLbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Odds between ähnelt.
        /// </summary>
        internal static string strASLS00OddsBetweenLbl {
            get {
                return ResourceManager.GetString("strASLS00OddsBetweenLbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Goal Sum between ähnelt.
        /// </summary>
        internal static string strASOUGoalSumLbl {
            get {
                return ResourceManager.GetString("strASOUGoalSumLbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Check Inplay ähnelt.
        /// </summary>
        internal static string strASSL00CheckIPCbx {
            get {
                return ResourceManager.GetString("strASSL00CheckIPCbx", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Check Preplay ähnelt.
        /// </summary>
        internal static string strASSL00CheckPPCbx {
            get {
                return ResourceManager.GetString("strASSL00CheckPPCbx", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Common ähnelt.
        /// </summary>
        internal static string strASSL00CommonGbx {
            get {
                return ResourceManager.GetString("strASSL00CommonGbx", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Equal Red Cards ähnelt.
        /// </summary>
        internal static string strASSL00EqualRCRbn {
            get {
                return ResourceManager.GetString("strASSL00EqualRCRbn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Inplay ähnelt.
        /// </summary>
        internal static string strASSL00InplayGbx {
            get {
                return ResourceManager.GetString("strASSL00InplayGbx", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Market Volume between ähnelt.
        /// </summary>
        internal static string strASSL00MarketVolumeLbl {
            get {
                return ResourceManager.GetString("strASSL00MarketVolumeLbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die &amp;New Range ähnelt.
        /// </summary>
        internal static string strASSL00NewRangeBtn {
            get {
                return ResourceManager.GetString("strASSL00NewRangeBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die No ähnelt.
        /// </summary>
        internal static string strASSL00NoRbn {
            get {
                return ResourceManager.GetString("strASSL00NoRbn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die No Red Cards ähnelt.
        /// </summary>
        internal static string strASSL00NoRCRbn {
            get {
                return ResourceManager.GetString("strASSL00NoRCRbn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Observe Red Cards ähnelt.
        /// </summary>
        internal static string strASSL00ObserveRCcbx {
            get {
                return ResourceManager.GetString("strASSL00ObserveRCcbx", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Playtime between ähnelt.
        /// </summary>
        internal static string strASSL00PlaytimeLbl {
            get {
                return ResourceManager.GetString("strASSL00PlaytimeLbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Preplay ähnelt.
        /// </summary>
        internal static string strASSL00PreplayGbx {
            get {
                return ResourceManager.GetString("strASSL00PreplayGbx", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Red Card Behaviour ähnelt.
        /// </summary>
        internal static string strASSL00RCBehaviourGbx {
            get {
                return ResourceManager.GetString("strASSL00RCBehaviourGbx", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Open Trade if there is a settled market ähnelt.
        /// </summary>
        internal static string strASSL00SettledMarketGbx {
            get {
                return ResourceManager.GetString("strASSL00SettledMarketGbx", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Statistics ähnelt.
        /// </summary>
        internal static string strASSL00StatisticsGbx {
            get {
                return ResourceManager.GetString("strASSL00StatisticsGbx", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Step has already traded ähnelt.
        /// </summary>
        internal static string strASSL00StepTakenChk {
            get {
                return ResourceManager.GetString("strASSL00StepTakenChk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Team A more Red Cards ähnelt.
        /// </summary>
        internal static string strASSL00TAMoreRCRbn {
            get {
                return ResourceManager.GetString("strASSL00TAMoreRCRbn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Team B more Red Cards ähnelt.
        /// </summary>
        internal static string strASSL00TBMoreRCRbn {
            get {
                return ResourceManager.GetString("strASSL00TBMoreRCRbn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Trade Configuration ähnelt.
        /// </summary>
        internal static string strASSL00TradeConfigBtn {
            get {
                return ResourceManager.GetString("strASSL00TradeConfigBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Open Trade if there is a unsettled market ähnelt.
        /// </summary>
        internal static string strASSL00UnsettledMarketGbx {
            get {
                return ResourceManager.GetString("strASSL00UnsettledMarketGbx", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Yes ähnelt.
        /// </summary>
        internal static string strASSL00YesRbn {
            get {
                return ResourceManager.GetString("strASSL00YesRbn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Error while loading Template ähnelt.
        /// </summary>
        internal static string strASTmpltOpenErrorCaption {
            get {
                return ResourceManager.GetString("strASTmpltOpenErrorCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die There was an error while opening file {0} ähnelt.
        /// </summary>
        internal static string strASTmpltOpenFileOpenError {
            get {
                return ResourceManager.GetString("strASTmpltOpenFileOpenError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Template File has no identification ähnelt.
        /// </summary>
        internal static string strASTmpltOpenNoType {
            get {
                return ResourceManager.GetString("strASTmpltOpenNoType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Template File is not a Trade The Reaction Template ähnelt.
        /// </summary>
        internal static string strASTmpltOpenWrongType {
            get {
                return ResourceManager.GetString("strASTmpltOpenWrongType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Successfully saved template:\r\n{0} ähnelt.
        /// </summary>
        internal static string strASTmpltSaveSuccMessage {
            get {
                return ResourceManager.GetString("strASTmpltSaveSuccMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Save Template ähnelt.
        /// </summary>
        internal static string strASTmpltSaveTitle {
            get {
                return ResourceManager.GetString("strASTmpltSaveTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Average 1st Goal ähnelt.
        /// </summary>
        internal static string strAverageFirstGoal {
            get {
                return ResourceManager.GetString("strAverageFirstGoal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Bet Amount ähnelt.
        /// </summary>
        internal static string strBetAmount {
            get {
                return ResourceManager.GetString("strBetAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Bet Odds ähnelt.
        /// </summary>
        internal static string strBetOdds {
            get {
                return ResourceManager.GetString("strBetOdds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die between ähnelt.
        /// </summary>
        internal static string strBetween {
            get {
                return ResourceManager.GetString("strBetween", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die &amp;Cancel ähnelt.
        /// </summary>
        internal static string strCancelBtn {
            get {
                return ResourceManager.GetString("strCancelBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Delta ähnelt.
        /// </summary>
        internal static string strCfgDelta {
            get {
                return ResourceManager.GetString("strCfgDelta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Always Bet ähnelt.
        /// </summary>
        internal static string strCfgFBAlwaysBet {
            get {
                return ResourceManager.GetString("strCfgFBAlwaysBet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Available Bankroll ähnelt.
        /// </summary>
        internal static string strCfgFBAvailableAmount {
            get {
                return ResourceManager.GetString("strCfgFBAvailableAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die % of ähnelt.
        /// </summary>
        internal static string strCfgFBPercentOf {
            get {
                return ResourceManager.GetString("strCfgFBPercentOf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die % of Total Bankroll ähnelt.
        /// </summary>
        internal static string strCfgFBTargetPercentOfBankroll {
            get {
                return ResourceManager.GetString("strCfgFBTargetPercentOfBankroll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Total Bankroll ähnelt.
        /// </summary>
        internal static string strCfgFBTotalAmount {
            get {
                return ResourceManager.GetString("strCfgFBTotalAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Fixed ähnelt.
        /// </summary>
        internal static string strCfgFixed {
            get {
                return ResourceManager.GetString("strCfgFixed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Amount of Minutes the Preplay Rule Check starts before Match begins: ähnelt.
        /// </summary>
        internal static string strCfgGenPreplayRuleStartMinuteLbl {
            get {
                return ResourceManager.GetString("strCfgGenPreplayRuleStartMinuteLbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Green ähnelt.
        /// </summary>
        internal static string strCfgGreen {
            get {
                return ResourceManager.GetString("strCfgGreen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Hedge ähnelt.
        /// </summary>
        internal static string strCfgHedge {
            get {
                return ResourceManager.GetString("strCfgHedge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die No Trade ähnelt.
        /// </summary>
        internal static string strCfgNoTrade {
            get {
                return ResourceManager.GetString("strCfgNoTrade", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Playtimes ähnelt.
        /// </summary>
        internal static string strCfgPlaytimes {
            get {
                return ResourceManager.GetString("strCfgPlaytimes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Check Lay Odds smaller than Back Odds ähnelt.
        /// </summary>
        internal static string strCfgSL00CheckLayOdds {
            get {
                return ResourceManager.GetString("strCfgSL00CheckLayOdds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Percentage of Back Odds Lay Odds must have before Greening: ähnelt.
        /// </summary>
        internal static string strCfgSL00GreenPercentage {
            get {
                return ResourceManager.GetString("strCfgSL00GreenPercentage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Wait Time before Greening in Seconds: ähnelt.
        /// </summary>
        internal static string strCfgSL00GreenWaitTime {
            get {
                return ResourceManager.GetString("strCfgSL00GreenWaitTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Percentage of Back Odds Lay Odds must have before Hedging: ähnelt.
        /// </summary>
        internal static string strCfgSL00HedgePercentage {
            get {
                return ResourceManager.GetString("strCfgSL00HedgePercentage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Wait Time before Hedging in Seconds: ähnelt.
        /// </summary>
        internal static string strCfgSL00HedgeWaitTime {
            get {
                return ResourceManager.GetString("strCfgSL00HedgeWaitTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Odds Percentage ähnelt.
        /// </summary>
        internal static string strCfgSL00OddsPercentage {
            get {
                return ResourceManager.GetString("strCfgSL00OddsPercentage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Only Hedge ähnelt.
        /// </summary>
        internal static string strCfgSL00OnlyHedge {
            get {
                return ResourceManager.GetString("strCfgSL00OnlyHedge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Calculate Target Lay Odds relativly to Back Odds ähnelt.
        /// </summary>
        internal static string strCfgSL00UseOddsPercentage {
            get {
                return ResourceManager.GetString("strCfgSL00UseOddsPercentage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Use Wait Times ähnelt.
        /// </summary>
        internal static string strCfgSL00UseWaitTime {
            get {
                return ResourceManager.GetString("strCfgSL00UseWaitTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Wait Times ähnelt.
        /// </summary>
        internal static string strCfgSL00WaitTime {
            get {
                return ResourceManager.GetString("strCfgSL00WaitTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Statistical ähnelt.
        /// </summary>
        internal static string strCfgStatistical {
            get {
                return ResourceManager.GetString("strCfgStatistical", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Change Odds by ähnelt.
        /// </summary>
        internal static string strChangeOddsBy {
            get {
                return ResourceManager.GetString("strChangeOddsBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Check Goal Sum ähnelt.
        /// </summary>
        internal static string strCheckGoalSum {
            get {
                return ResourceManager.GetString("strCheckGoalSum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Check Lay Odds ähnelt.
        /// </summary>
        internal static string strCheckLayOdds {
            get {
                return ResourceManager.GetString("strCheckLayOdds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Check Order ähnelt.
        /// </summary>
        internal static string strCheckOrder {
            get {
                return ResourceManager.GetString("strCheckOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Check Playtime ähnelt.
        /// </summary>
        internal static string strCheckPlaytime {
            get {
                return ResourceManager.GetString("strCheckPlaytime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Check Rules ähnelt.
        /// </summary>
        internal static string strCheckRules {
            get {
                return ResourceManager.GetString("strCheckRules", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Check Scores ähnelt.
        /// </summary>
        internal static string strCheckScores {
            get {
                return ResourceManager.GetString("strCheckScores", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Correct Score ähnelt.
        /// </summary>
        internal static string strCorrectScore {
            get {
                return ResourceManager.GetString("strCorrectScore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Delta ähnelt.
        /// </summary>
        internal static string strDelta {
            get {
                return ResourceManager.GetString("strDelta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Trades on Soccer Markets ähnelt.
        /// </summary>
        internal static string strDescription {
            get {
                return ResourceManager.GetString("strDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Score Selection ähnelt.
        /// </summary>
        internal static string strDlgScoreSelection {
            get {
                return ResourceManager.GetString("strDlgScoreSelection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Earlist 1st Goal ähnelt.
        /// </summary>
        internal static string strEarliestGoal {
            get {
                return ResourceManager.GetString("strEarliestGoal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Equal Red Cards ähnelt.
        /// </summary>
        internal static string strEqualRCR {
            get {
                return ResourceManager.GetString("strEqualRCR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Error ähnelt.
        /// </summary>
        internal static string strError {
            get {
                return ResourceManager.GetString("strError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Soccer/Trade The Reaction ähnelt.
        /// </summary>
        internal static string strFQTradeTheReaction {
            get {
                return ResourceManager.GetString("strFQTradeTheReaction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die General ähnelt.
        /// </summary>
        internal static string strGeneral {
            get {
                return ResourceManager.GetString("strGeneral", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Goal ähnelt.
        /// </summary>
        internal static string strGoal {
            get {
                return ResourceManager.GetString("strGoal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Goal Sum ähnelt.
        /// </summary>
        internal static string strGoalSum {
            get {
                return ResourceManager.GetString("strGoalSum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Greened ähnelt.
        /// </summary>
        internal static string strGreened {
            get {
                return ResourceManager.GetString("strGreened", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Green Percentage ähnelt.
        /// </summary>
        internal static string strGreenPercentage {
            get {
                return ResourceManager.GetString("strGreenPercentage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Green Playtime ähnelt.
        /// </summary>
        internal static string strGreenPlaytime {
            get {
                return ResourceManager.GetString("strGreenPlaytime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Greening Special Playtime ähnelt.
        /// </summary>
        internal static string strGreenSpecialTime {
            get {
                return ResourceManager.GetString("strGreenSpecialTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Green Wait Time ähnelt.
        /// </summary>
        internal static string strGreenWaittime {
            get {
                return ResourceManager.GetString("strGreenWaittime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Hedged ähnelt.
        /// </summary>
        internal static string strHedged {
            get {
                return ResourceManager.GetString("strHedged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Only Hedge ähnelt.
        /// </summary>
        internal static string strHedgeOnly {
            get {
                return ResourceManager.GetString("strHedgeOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Hedge Percentage ähnelt.
        /// </summary>
        internal static string strHedgePercentage {
            get {
                return ResourceManager.GetString("strHedgePercentage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Hedge Playtime ähnelt.
        /// </summary>
        internal static string strHedgePlaytime {
            get {
                return ResourceManager.GetString("strHedgePlaytime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Hedging Special Playtime ähnelt.
        /// </summary>
        internal static string strHedgeSpecialTime {
            get {
                return ResourceManager.GetString("strHedgeSpecialTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Hedge Wait Time ähnelt.
        /// </summary>
        internal static string strHedgeWaitTime {
            get {
                return ResourceManager.GetString("strHedgeWaitTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Keep Inplay ähnelt.
        /// </summary>
        internal static string strKeepInplay {
            get {
                return ResourceManager.GetString("strKeepInplay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Keep Unmatched ähnelt.
        /// </summary>
        internal static string strKeepUnmatched {
            get {
                return ResourceManager.GetString("strKeepUnmatched", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Latest 1st Goal ähnelt.
        /// </summary>
        internal static string strLatestFirstGoal {
            get {
                return ResourceManager.GetString("strLatestFirstGoal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The upper end of the Market Volume interval must be greater than the lower end. ähnelt.
        /// </summary>
        internal static string strMarketVolumeHighLowMismatch {
            get {
                return ResourceManager.GetString("strMarketVolumeHighLowMismatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Match added. ähnelt.
        /// </summary>
        internal static string strMatchAdded {
            get {
                return ResourceManager.GetString("strMatchAdded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die State has changed from {0} to {1} ähnelt.
        /// </summary>
        internal static string strMsgTradeStateChanged {
            get {
                return ResourceManager.GetString("strMsgTradeStateChanged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Trade The Reaction ähnelt.
        /// </summary>
        internal static string strName {
            get {
                return ResourceManager.GetString("strName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Please select a match first. ähnelt.
        /// </summary>
        internal static string strNoMatchSelected {
            get {
                return ResourceManager.GetString("strNoMatchSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die No Matter ähnelt.
        /// </summary>
        internal static string strNoMatter {
            get {
                return ResourceManager.GetString("strNoMatter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die No Parameter was provided in Module {0} ähnelt.
        /// </summary>
        internal static string strNoParameter {
            get {
                return ResourceManager.GetString("strNoParameter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die No Red Card Check ähnelt.
        /// </summary>
        internal static string strNoRCCheck {
            get {
                return ResourceManager.GetString("strNoRCCheck", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die No Trading! ähnelt.
        /// </summary>
        internal static string strNoTrading {
            get {
                return ResourceManager.GetString("strNoTrading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The upper end of the odds interval must be greater than the lower end. ähnelt.
        /// </summary>
        internal static string strOddsHighLowMismatch {
            get {
                return ResourceManager.GetString("strOddsHighLowMismatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die &amp;OK ähnelt.
        /// </summary>
        internal static string strOKBtn {
            get {
                return ResourceManager.GetString("strOKBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Opened ähnelt.
        /// </summary>
        internal static string strOpened {
            get {
                return ResourceManager.GetString("strOpened", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Options ähnelt.
        /// </summary>
        internal static string strOptions {
            get {
                return ResourceManager.GetString("strOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Order ähnelt.
        /// </summary>
        internal static string strOrder {
            get {
                return ResourceManager.GetString("strOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Other ähnelt.
        /// </summary>
        internal static string strOther {
            get {
                return ResourceManager.GetString("strOther", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Over 0.5 ähnelt.
        /// </summary>
        internal static string strOver05 {
            get {
                return ResourceManager.GetString("strOver05", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Over 1.5 ähnelt.
        /// </summary>
        internal static string strOver15 {
            get {
                return ResourceManager.GetString("strOver15", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Over 2.5 ähnelt.
        /// </summary>
        internal static string strOver25 {
            get {
                return ResourceManager.GetString("strOver25", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Over 3.5 ähnelt.
        /// </summary>
        internal static string strOver35 {
            get {
                return ResourceManager.GetString("strOver35", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Over 4.5 ähnelt.
        /// </summary>
        internal static string strOver45 {
            get {
                return ResourceManager.GetString("strOver45", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Over 5.5 ähnelt.
        /// </summary>
        internal static string strOver55 {
            get {
                return ResourceManager.GetString("strOver55", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Over 6.5 ähnelt.
        /// </summary>
        internal static string strOver65 {
            get {
                return ResourceManager.GetString("strOver65", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Over 7.5 ähnelt.
        /// </summary>
        internal static string strOver75 {
            get {
                return ResourceManager.GetString("strOver75", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Over 8.5 ähnelt.
        /// </summary>
        internal static string strOver85 {
            get {
                return ResourceManager.GetString("strOver85", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Over/Under ähnelt.
        /// </summary>
        internal static string strOverUnder {
            get {
                return ResourceManager.GetString("strOverUnder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Profit/Loss Snapshot ähnelt.
        /// </summary>
        internal static string strOvwPLSnapshot {
            get {
                return ResourceManager.GetString("strOvwPLSnapshot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Average Back Odds: ähnelt.
        /// </summary>
        internal static string strOvwSL00AvgBackOddsLbl {
            get {
                return ResourceManager.GetString("strOvwSL00AvgBackOddsLbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Average Back Amount: ähnelt.
        /// </summary>
        internal static string strOvwSL00AvgBackPriceLbl {
            get {
                return ResourceManager.GetString("strOvwSL00AvgBackPriceLbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Average Lay Odds: ähnelt.
        /// </summary>
        internal static string strOvwSL00AvgLayOddsLbl {
            get {
                return ResourceManager.GetString("strOvwSL00AvgLayOddsLbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Average Lay Amount: ähnelt.
        /// </summary>
        internal static string strOvwSL00AvgLayPriceLbl {
            get {
                return ResourceManager.GetString("strOvwSL00AvgLayPriceLbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Trade State: ähnelt.
        /// </summary>
        internal static string strOvwSL00TradeStateLbl {
            get {
                return ResourceManager.GetString("strOvwSL00TradeStateLbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die % ähnelt.
        /// </summary>
        internal static string strPercent {
            get {
                return ResourceManager.GetString("strPercent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Playtime ähnelt.
        /// </summary>
        internal static string strPlaytime {
            get {
                return ResourceManager.GetString("strPlaytime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The upper end of the Playtime interval must be greater than the lower end. ähnelt.
        /// </summary>
        internal static string strPlaytimeHighLowMismatch {
            get {
                return ResourceManager.GetString("strPlaytimeHighLowMismatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Plugin {0} loaded ähnelt.
        /// </summary>
        internal static string strPluginLoaded {
            get {
                return ResourceManager.GetString("strPluginLoaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Both Team Equal Red Cards ähnelt.
        /// </summary>
        internal static string strRCEqual {
            get {
                return ResourceManager.GetString("strRCEqual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Red Card ähnelt.
        /// </summary>
        internal static string strRedCard {
            get {
                return ResourceManager.GetString("strRedCard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Rule ID ähnelt.
        /// </summary>
        internal static string strRuleId {
            get {
                return ResourceManager.GetString("strRuleId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Score ähnelt.
        /// </summary>
        internal static string strScore {
            get {
                return ResourceManager.GetString("strScore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Scoreline 0 - 0 ähnelt.
        /// </summary>
        internal static string strScoreLine00 {
            get {
                return ResourceManager.GetString("strScoreLine00", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Scoreline 0 - 0 Back ähnelt.
        /// </summary>
        internal static string strScoreline00Back {
            get {
                return ResourceManager.GetString("strScoreline00Back", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Scoreline 0 - 0 Lay ähnelt.
        /// </summary>
        internal static string strScoreline00Lay {
            get {
                return ResourceManager.GetString("strScoreline00Lay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Scoreline 0 - 1 Back ähnelt.
        /// </summary>
        internal static string strScoreline01Back {
            get {
                return ResourceManager.GetString("strScoreline01Back", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Scoreline 0 - 1 Lay ähnelt.
        /// </summary>
        internal static string strScoreline01Lay {
            get {
                return ResourceManager.GetString("strScoreline01Lay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Scoreline 0 - 2 Back ähnelt.
        /// </summary>
        internal static string strScoreline02Back {
            get {
                return ResourceManager.GetString("strScoreline02Back", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Scoreline 0 - 2 Lay ähnelt.
        /// </summary>
        internal static string strScoreline02Lay {
            get {
                return ResourceManager.GetString("strScoreline02Lay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Scoreline 0 - 3 Back ähnelt.
        /// </summary>
        internal static string strScoreline03Back {
            get {
                return ResourceManager.GetString("strScoreline03Back", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Scoreline 0 - 3 Lay ähnelt.
        /// </summary>
        internal static string strScoreline03Lay {
            get {
                return ResourceManager.GetString("strScoreline03Lay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Scoreline 1 - 0 Back ähnelt.
        /// </summary>
        internal static string strScoreline10Back {
            get {
                return ResourceManager.GetString("strScoreline10Back", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Scoreline 1 - 0 Lay ähnelt.
        /// </summary>
        internal static string strScoreline10Lay {
            get {
                return ResourceManager.GetString("strScoreline10Lay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Scoreline 1 - 1 Back ähnelt.
        /// </summary>
        internal static string strScoreline11Back {
            get {
                return ResourceManager.GetString("strScoreline11Back", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Scoreline 1 - 1 Lay ähnelt.
        /// </summary>
        internal static string strScoreline11Lay {
            get {
                return ResourceManager.GetString("strScoreline11Lay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Scoreline 1 - 2 Back ähnelt.
        /// </summary>
        internal static string strScoreline12Back {
            get {
                return ResourceManager.GetString("strScoreline12Back", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Scoreline 1 - 2 Lay ähnelt.
        /// </summary>
        internal static string strScoreline12Lay {
            get {
                return ResourceManager.GetString("strScoreline12Lay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Scoreline 1- 3 Back ähnelt.
        /// </summary>
        internal static string strScoreline13Back {
            get {
                return ResourceManager.GetString("strScoreline13Back", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Scoreline 1 - 3 Lay ähnelt.
        /// </summary>
        internal static string strScoreline13Lay {
            get {
                return ResourceManager.GetString("strScoreline13Lay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Scoreline 2 - 0 Back ähnelt.
        /// </summary>
        internal static string strScoreline20Back {
            get {
                return ResourceManager.GetString("strScoreline20Back", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Scoreline 2 - 0 Lay ähnelt.
        /// </summary>
        internal static string strScoreline20Lay {
            get {
                return ResourceManager.GetString("strScoreline20Lay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Scoreline 2 - 1 Back ähnelt.
        /// </summary>
        internal static string strScoreline21Back {
            get {
                return ResourceManager.GetString("strScoreline21Back", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Scoreline 2 - 1 Lay ähnelt.
        /// </summary>
        internal static string strScoreline21Lay {
            get {
                return ResourceManager.GetString("strScoreline21Lay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Scoreline 2 - 2 Back ähnelt.
        /// </summary>
        internal static string strScoreline22Back {
            get {
                return ResourceManager.GetString("strScoreline22Back", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Scoreline 2 - 2 Lay ähnelt.
        /// </summary>
        internal static string strScoreline22Lay {
            get {
                return ResourceManager.GetString("strScoreline22Lay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Scoreline 2 - 3 Back ähnelt.
        /// </summary>
        internal static string strScoreline23Back {
            get {
                return ResourceManager.GetString("strScoreline23Back", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Scoreline 2 - 3 Lay ähnelt.
        /// </summary>
        internal static string strScoreline23Lay {
            get {
                return ResourceManager.GetString("strScoreline23Lay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Scoreline 3 - 0 Back ähnelt.
        /// </summary>
        internal static string strScoreline30Back {
            get {
                return ResourceManager.GetString("strScoreline30Back", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Scoreline 3 - 0 Lay ähnelt.
        /// </summary>
        internal static string strScoreline30Lay {
            get {
                return ResourceManager.GetString("strScoreline30Lay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Scoreline 3 - 1 Back ähnelt.
        /// </summary>
        internal static string strScoreline31Back {
            get {
                return ResourceManager.GetString("strScoreline31Back", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Scoreline 3 - 1 Lay ähnelt.
        /// </summary>
        internal static string strScoreline31Lay {
            get {
                return ResourceManager.GetString("strScoreline31Lay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Scoreline 3 - 2 Back ähnelt.
        /// </summary>
        internal static string strScoreline32Back {
            get {
                return ResourceManager.GetString("strScoreline32Back", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Scoreline 3 - 2 Lay ähnelt.
        /// </summary>
        internal static string strScoreline32Lay {
            get {
                return ResourceManager.GetString("strScoreline32Lay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Scoreline 3 - 3 Back ähnelt.
        /// </summary>
        internal static string strScoreline33Back {
            get {
                return ResourceManager.GetString("strScoreline33Back", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Scoreline 3 - 3 Lay ähnelt.
        /// </summary>
        internal static string strScoreline33Lay {
            get {
                return ResourceManager.GetString("strScoreline33Lay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Scoreline Other Lay ähnelt.
        /// </summary>
        internal static string strScorelineOtherLay {
            get {
                return ResourceManager.GetString("strScorelineOtherLay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Scoreline Other Back ähnelt.
        /// </summary>
        internal static string strScorelineOthersBack {
            get {
                return ResourceManager.GetString("strScorelineOthersBack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Scores:  ähnelt.
        /// </summary>
        internal static string strScoresASBtn {
            get {
                return ResourceManager.GetString("strScoresASBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Seconds ähnelt.
        /// </summary>
        internal static string strSeconds {
            get {
                return ResourceManager.GetString("strSeconds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Stake ähnelt.
        /// </summary>
        internal static string strStake {
            get {
                return ResourceManager.GetString("strStake", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Team A More Red Cards Check ähnelt.
        /// </summary>
        internal static string strTAMoreRCCheck {
            get {
                return ResourceManager.GetString("strTAMoreRCCheck", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Team A more Red Cards ähnelt.
        /// </summary>
        internal static string strTAMoreRCR {
            get {
                return ResourceManager.GetString("strTAMoreRCR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Team B More Red Cards Check ähnelt.
        /// </summary>
        internal static string strTBMoreRCCheck {
            get {
                return ResourceManager.GetString("strTBMoreRCCheck", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Team B more Red Cards ähnelt.
        /// </summary>
        internal static string strTBMoreRCR {
            get {
                return ResourceManager.GetString("strTBMoreRCR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Ticks. ähnelt.
        /// </summary>
        internal static string strTicks {
            get {
                return ResourceManager.GetString("strTicks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Back:  - Ticks. Lay: + Ticks ähnelt.
        /// </summary>
        internal static string strTicksExplain {
            get {
                return ResourceManager.GetString("strTicksExplain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Trading Out Rules ähnelt.
        /// </summary>
        internal static string strTitelTradeOutRulesDlg {
            get {
                return ResourceManager.GetString("strTitelTradeOutRulesDlg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Total ähnelt.
        /// </summary>
        internal static string strTotal {
            get {
                return ResourceManager.GetString("strTotal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Trade Out Rule ähnelt.
        /// </summary>
        internal static string strTradeOutRule {
            get {
                return ResourceManager.GetString("strTradeOutRule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Trade Out Setting ähnelt.
        /// </summary>
        internal static string strTradeOutSetting {
            get {
                return ResourceManager.GetString("strTradeOutSetting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Trigger ähnelt.
        /// </summary>
        internal static string strTrigger {
            get {
                return ResourceManager.GetString("strTrigger", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die General ähnelt.
        /// </summary>
        internal static string strTriggerGeneral {
            get {
                return ResourceManager.GetString("strTriggerGeneral", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Goal Scored ähnelt.
        /// </summary>
        internal static string strTriggerGoalScored {
            get {
                return ResourceManager.GetString("strTriggerGoalScored", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Red Card ähnelt.
        /// </summary>
        internal static string strTriggerRedCard {
            get {
                return ResourceManager.GetString("strTriggerRedCard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Local Configuration ähnelt.
        /// </summary>
        internal static string strTTRLocalConfigTitel {
            get {
                return ResourceManager.GetString("strTTRLocalConfigTitel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Unassigned ähnelt.
        /// </summary>
        internal static string strUnassigned {
            get {
                return ResourceManager.GetString("strUnassigned", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Use given Odds ähnelt.
        /// </summary>
        internal static string strUseGivenOdds {
            get {
                return ResourceManager.GetString("strUseGivenOdds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Use Green Minutes ähnelt.
        /// </summary>
        internal static string strUseGreenMinutes {
            get {
                return ResourceManager.GetString("strUseGreenMinutes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Use Hedge Wait Time ähnelt.
        /// </summary>
        internal static string strUseHedgeWaitTime {
            get {
                return ResourceManager.GetString("strUseHedgeWaitTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Use Odds Percentage ähnelt.
        /// </summary>
        internal static string strUseOddsPercentage {
            get {
                return ResourceManager.GetString("strUseOddsPercentage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Use Wait Time ähnelt.
        /// </summary>
        internal static string strUseWaitTime {
            get {
                return ResourceManager.GetString("strUseWaitTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Winning ähnelt.
        /// </summary>
        internal static string strWinning {
            get {
                return ResourceManager.GetString("strWinning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Too many or too less parameters provided in Module {0} ähnelt.
        /// </summary>
        internal static string strWrongParameterCount {
            get {
                return ResourceManager.GetString("strWrongParameterCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Parameter {0}: Wrong Parametertype. Expected Parametertype {1} ähnelt.
        /// </summary>
        internal static string strWrongParameterType {
            get {
                return ResourceManager.GetString("strWrongParameterType", resourceCulture);
            }
        }
    }
}
