//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.34011
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace net.sxtrader.bftradingstrategies.sxstatisticbase {
    using System;
    
    
    /// <summary>
    ///   Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    /// </summary>
    // Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    // -Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    // Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    // mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class SXStatisticBase {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SXStatisticBase() {
        }
        
        /// <summary>
        ///   Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("net.sxtrader.bftradingstrategies.sxstatisticbase.SXStatisticBase", typeof(SXStatisticBase).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        ///   Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die and ähnelt.
        /// </summary>
        internal static string strAnd {
            get {
                return ResourceManager.GetString("strAnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Average 1st Goal Time ähnelt.
        /// </summary>
        internal static string strAvgFirstGoal {
            get {
                return ResourceManager.GetString("strAvgFirstGoal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Average Goals ähnelt.
        /// </summary>
        internal static string strAvgGoals {
            get {
                return ResourceManager.GetString("strAvgGoals", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Between ähnelt.
        /// </summary>
        internal static string strBetween {
            get {
                return ResourceManager.GetString("strBetween", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die &amp;Delete ähnelt.
        /// </summary>
        internal static string strDeleteBtn {
            get {
                return ResourceManager.GetString("strDeleteBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Draw ähnelt.
        /// </summary>
        internal static string strDraw {
            get {
                return ResourceManager.GetString("strDraw", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Earliest 1st Goal Time ähnelt.
        /// </summary>
        internal static string strEarliestFirstGoal {
            get {
                return ResourceManager.GetString("strEarliestFirstGoal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Away ähnelt.
        /// </summary>
        internal static string strHomeAwayAway {
            get {
                return ResourceManager.GetString("strHomeAwayAway", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Home and Away ähnelt.
        /// </summary>
        internal static string strHomeAwayBoth {
            get {
                return ResourceManager.GetString("strHomeAwayBoth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Home ähnelt.
        /// </summary>
        internal static string strHomeAwayHome {
            get {
                return ResourceManager.GetString("strHomeAwayHome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Latest 1st Goal Time ähnelt.
        /// </summary>
        internal static string strLatestFirstGoal {
            get {
                return ResourceManager.GetString("strLatestFirstGoal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Loss ähnelt.
        /// </summary>
        internal static string strLoss {
            get {
                return ResourceManager.GetString("strLoss", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Number of Data ähnelt.
        /// </summary>
        internal static string strNoOfData {
            get {
                return ResourceManager.GetString("strNoOfData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Over 0.5 ähnelt.
        /// </summary>
        internal static string strOver05 {
            get {
                return ResourceManager.GetString("strOver05", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Over 1.5 ähnelt.
        /// </summary>
        internal static string strOver15 {
            get {
                return ResourceManager.GetString("strOver15", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Over 2.5 ähnelt.
        /// </summary>
        internal static string strOver25 {
            get {
                return ResourceManager.GetString("strOver25", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Over 3.5 ähnelt.
        /// </summary>
        internal static string strOver35 {
            get {
                return ResourceManager.GetString("strOver35", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Over 4.5 ähnelt.
        /// </summary>
        internal static string strOver45 {
            get {
                return ResourceManager.GetString("strOver45", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Score 0 - 0 ähnelt.
        /// </summary>
        internal static string strScore00 {
            get {
                return ResourceManager.GetString("strScore00", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Score 0 - 1 ähnelt.
        /// </summary>
        internal static string strScore01 {
            get {
                return ResourceManager.GetString("strScore01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Score 0 - 2 ähnelt.
        /// </summary>
        internal static string strScore02 {
            get {
                return ResourceManager.GetString("strScore02", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Score 0 - 3 ähnelt.
        /// </summary>
        internal static string strScore03 {
            get {
                return ResourceManager.GetString("strScore03", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Score 1 - 0 ähnelt.
        /// </summary>
        internal static string strScore10 {
            get {
                return ResourceManager.GetString("strScore10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Score 1 - 1 ähnelt.
        /// </summary>
        internal static string strScore11 {
            get {
                return ResourceManager.GetString("strScore11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Score 1 - 2 ähnelt.
        /// </summary>
        internal static string strScore12 {
            get {
                return ResourceManager.GetString("strScore12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Score 1 - 3 ähnelt.
        /// </summary>
        internal static string strScore13 {
            get {
                return ResourceManager.GetString("strScore13", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Score 2 - 0 ähnelt.
        /// </summary>
        internal static string strScore20 {
            get {
                return ResourceManager.GetString("strScore20", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Score 2 - 1 ähnelt.
        /// </summary>
        internal static string strScore21 {
            get {
                return ResourceManager.GetString("strScore21", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Score 2 - 2 ähnelt.
        /// </summary>
        internal static string strScore22 {
            get {
                return ResourceManager.GetString("strScore22", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Score 2 - 3 ähnelt.
        /// </summary>
        internal static string strScore23 {
            get {
                return ResourceManager.GetString("strScore23", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Score 3 - 0 ähnelt.
        /// </summary>
        internal static string strScore30 {
            get {
                return ResourceManager.GetString("strScore30", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Score 3 - 1 ähnelt.
        /// </summary>
        internal static string strScore31 {
            get {
                return ResourceManager.GetString("strScore31", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Score 3 - 2 ähnelt.
        /// </summary>
        internal static string strScore32 {
            get {
                return ResourceManager.GetString("strScore32", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Score 3 - 3 ähnelt.
        /// </summary>
        internal static string strScore33 {
            get {
                return ResourceManager.GetString("strScore33", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Score Others ähnelt.
        /// </summary>
        internal static string strScoreOther {
            get {
                return ResourceManager.GetString("strScoreOther", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Team A ähnelt.
        /// </summary>
        internal static string strTeamA {
            get {
                return ResourceManager.GetString("strTeamA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Team B ähnelt.
        /// </summary>
        internal static string strTeamB {
            get {
                return ResourceManager.GetString("strTeamB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Both Teams ähnelt.
        /// </summary>
        internal static string strTeamBoth {
            get {
                return ResourceManager.GetString("strTeamBoth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Win ähnelt.
        /// </summary>
        internal static string strWin {
            get {
                return ResourceManager.GetString("strWin", resourceCulture);
            }
        }
    }
}
