//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.18052
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace net.sxtrader.bftradingstrategies.BackThe4 {
    using System;
    
    
    /// <summary>
    ///   Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    /// </summary>
    // Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    // -Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    // Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    // mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class BackThe4 {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal BackThe4() {
        }
        
        /// <summary>
        ///   Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("net.sxtrader.bftradingstrategies.BackThe4.BackThe4", typeof(BackThe4).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        ///   Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Add Livescore ähnelt.
        /// </summary>
        internal static string strAddLivescore {
            get {
                return ResourceManager.GetString("strAddLivescore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Back The 4 ähnelt.
        /// </summary>
        internal static string strBackThe4 {
            get {
                return ResourceManager.GetString("strBackThe4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Back the Total Goals of 4  and Lay it after a goal was scored ähnelt.
        /// </summary>
        internal static string strBackThe4Descr {
            get {
                return ResourceManager.GetString("strBackThe4Descr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Browse... ähnelt.
        /// </summary>
        internal static string strBrowse {
            get {
                return ResourceManager.GetString("strBrowse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die &amp;Cancel ähnelt.
        /// </summary>
        internal static string strCancel {
            get {
                return ResourceManager.GetString("strCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Close Trade Behavior ähnelt.
        /// </summary>
        internal static string strCloseTradeBehavior {
            get {
                return ResourceManager.GetString("strCloseTradeBehavior", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Configuration Back The 4 ähnelt.
        /// </summary>
        internal static string strConfigBT4 {
            get {
                return ResourceManager.GetString("strConfigBT4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Strategy activated by default? ähnelt.
        /// </summary>
        internal static string strDefaultActivation {
            get {
                return ResourceManager.GetString("strDefaultActivation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die % don&apos;t close trade ähnelt.
        /// </summary>
        internal static string strDontClose {
            get {
                return ResourceManager.GetString("strDontClose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die times of average Back-Odds ähnelt.
        /// </summary>
        internal static string strEndBackOdds {
            get {
                return ResourceManager.GetString("strEndBackOdds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die FileGameEndedSound ähnelt.
        /// </summary>
        internal static string strFileGameEndedSound {
            get {
                return ResourceManager.GetString("strFileGameEndedSound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die FileMatchAddedSound ähnelt.
        /// </summary>
        internal static string strFileMatchAddedSound {
            get {
                return ResourceManager.GetString("strFileMatchAddedSound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die FileScoreChangedSound ähnelt.
        /// </summary>
        internal static string strFileScoreChangedSound {
            get {
                return ResourceManager.GetString("strFileScoreChangedSound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die FileTradingChangedSound ähnelt.
        /// </summary>
        internal static string strFileTradingChangedSound {
            get {
                return ResourceManager.GetString("strFileTradingChangedSound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Soccer/Back The 4 ähnelt.
        /// </summary>
        internal static string strFQBackThe4 {
            get {
                return ResourceManager.GetString("strFQBackThe4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Game Ended ähnelt.
        /// </summary>
        internal static string strGameEnded {
            get {
                return ResourceManager.GetString("strGameEnded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Goals ähnelt.
        /// </summary>
        internal static string strGoals {
            get {
                return ResourceManager.GetString("strGoals", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die minutes if trade isn&apos;t completed ähnelt.
        /// </summary>
        internal static string strIsntCompleted {
            get {
                return ResourceManager.GetString("strIsntCompleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Livescore 1 ähnelt.
        /// </summary>
        internal static string strLivescore1 {
            get {
                return ResourceManager.GetString("strLivescore1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Livescore 2 ähnelt.
        /// </summary>
        internal static string strLivescore2 {
            get {
                return ResourceManager.GetString("strLivescore2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Local Configuration for Single Match ähnelt.
        /// </summary>
        internal static string strLocalConfig {
            get {
                return ResourceManager.GetString("strLocalConfig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die but lower than ähnelt.
        /// </summary>
        internal static string strLowerThan {
            get {
                return ResourceManager.GetString("strLowerThan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Match Added ähnelt.
        /// </summary>
        internal static string strMatchAdded {
            get {
                return ResourceManager.GetString("strMatchAdded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die minutes of playtime ähnelt.
        /// </summary>
        internal static string strMinutesOfPlaytime {
            get {
                return ResourceManager.GetString("strMinutesOfPlaytime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Back The 4 ähnelt.
        /// </summary>
        internal static string strModule {
            get {
                return ResourceManager.GetString("strModule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die No Livescore ähnelt.
        /// </summary>
        internal static string strNoLivescore {
            get {
                return ResourceManager.GetString("strNoLivescore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die No Parameter was provided in Module {0} ähnelt.
        /// </summary>
        internal static string strNoParameter {
            get {
                return ResourceManager.GetString("strNoParameter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Close trade even if there&apos;s no profit ähnelt.
        /// </summary>
        internal static string strNoProfit {
            get {
                return ResourceManager.GetString("strNoProfit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die &amp;OK ähnelt.
        /// </summary>
        internal static string strOK {
            get {
                return ResourceManager.GetString("strOK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Place Lay-Bet for Market {0} with Odds {1} for {2} € ähnelt.
        /// </summary>
        internal static string strPlaceBet {
            get {
                return ResourceManager.GetString("strPlaceBet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Play ähnelt.
        /// </summary>
        internal static string strPlay {
            get {
                return ResourceManager.GetString("strPlay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die PlayMatchEndedSound ähnelt.
        /// </summary>
        internal static string strPlayGameEndedSound {
            get {
                return ResourceManager.GetString("strPlayGameEndedSound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die PlayMatchAddedSound ähnelt.
        /// </summary>
        internal static string strPlayMatchAddedSound {
            get {
                return ResourceManager.GetString("strPlayMatchAddedSound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die PlayScoreChangedSound ähnelt.
        /// </summary>
        internal static string strPlayScoreChangedSound {
            get {
                return ResourceManager.GetString("strPlayScoreChangedSound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Play Sounds ähnelt.
        /// </summary>
        internal static string strPlaySounds {
            get {
                return ResourceManager.GetString("strPlaySounds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Play Sounds ähnelt.
        /// </summary>
        internal static string strPlaySoundsText {
            get {
                return ResourceManager.GetString("strPlaySoundsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Minutes of Playtime ähnelt.
        /// </summary>
        internal static string strPlaytimeMinute {
            get {
                return ResourceManager.GetString("strPlaytimeMinute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die PlayTradingChangedSound ähnelt.
        /// </summary>
        internal static string strPlayTradingChangedSound {
            get {
                return ResourceManager.GetString("strPlayTradingChangedSound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Plugin {0} was activated ähnelt.
        /// </summary>
        internal static string strPluginActivated {
            get {
                return ResourceManager.GetString("strPluginActivated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Plugin {0} was deactivated ähnelt.
        /// </summary>
        internal static string strPluginDeactivated {
            get {
                return ResourceManager.GetString("strPluginDeactivated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Plugin {0} loaded ähnelt.
        /// </summary>
        internal static string strPluginLoaded {
            get {
                return ResourceManager.GetString("strPluginLoaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die If profit is lower than ähnelt.
        /// </summary>
        internal static string strProfitLower {
            get {
                return ResourceManager.GetString("strProfitLower", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Restart trade after ähnelt.
        /// </summary>
        internal static string strRestartTrade {
            get {
                return ResourceManager.GetString("strRestartTrade", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Score Changed ähnelt.
        /// </summary>
        internal static string strScoreChanged {
            get {
                return ResourceManager.GetString("strScoreChanged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die seconds before starting trade ähnelt.
        /// </summary>
        internal static string strSecondsBefore {
            get {
                return ResourceManager.GetString("strSecondsBefore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Sound ähnelt.
        /// </summary>
        internal static string strSound {
            get {
                return ResourceManager.GetString("strSound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Start Close-Trade after ähnelt.
        /// </summary>
        internal static string strStartClose {
            get {
                return ResourceManager.GetString("strStartClose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Start Stop/Loss after ähnelt.
        /// </summary>
        internal static string strStartStopLoss {
            get {
                return ResourceManager.GetString("strStartStopLoss", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Stop/Loss Behavior ähnelt.
        /// </summary>
        internal static string strStopLossBehavior {
            get {
                return ResourceManager.GetString("strStopLossBehavior", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Start Stop/Loss-Trade when Lay-Odds are ähnelt.
        /// </summary>
        internal static string strStopLossOdds {
            get {
                return ResourceManager.GetString("strStopLossOdds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Strategy Controlling ähnelt.
        /// </summary>
        internal static string strStrategyControl {
            get {
                return ResourceManager.GetString("strStrategyControl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die times of average Back-Odds ähnelt.
        /// </summary>
        internal static string strTimes {
            get {
                return ResourceManager.GetString("strTimes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Trading Changed ähnelt.
        /// </summary>
        internal static string strTradingChanged {
            get {
                return ResourceManager.GetString("strTradingChanged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Wait ähnelt.
        /// </summary>
        internal static string strWait {
            get {
                return ResourceManager.GetString("strWait", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Too many or too less parameters provided in Module {0} ähnelt.
        /// </summary>
        internal static string strWrongParameterCount {
            get {
                return ResourceManager.GetString("strWrongParameterCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Parameter {0}: Wrong Parametertype. Expected Parametertype {1} ähnelt.
        /// </summary>
        internal static string strWrongParameterType {
            get {
                return ResourceManager.GetString("strWrongParameterType", resourceCulture);
            }
        }
    }
}
